// For Logic
export const ProControllerConfig: { [key: string]: number } = {
  A: 0,
  B: 1,
  X: 2,
  Y: 3,
  LB: 4,
  RB: 5,
  LT: 6,
  RT: 7,
  Back: 8,
  Start: 9,
  LS: 10,
  RS: 11,
  DPadUp: 12,
  DPadDown: 13,
  DPadLeft: 14,
  DPadRight: 15,
  LeftStickX: 18,
  LeftStickY: 19,
  RightStickX: 20,
  RightStickY: 21,
  LeftTrigger: 6,
  RightTrigger: 7,
};

// For Display (PS5 DualSense labels; SVG layout from PhantomHand — see README credits)
export const ProControllerButtonNames: { [key: number]: string } = {
  0: "Circle",
  1: "Cross",
  2: "Triangle",
  3: "Square",
  4: "L1",
  5: "R1",
  6: "L2",
  7: "R2",
  8: "Create",
  9: "Options",
  10: "L3",
  11: "R3",
  12: "↑",
  13: "↓",
  14: "←",
  15: "→",
  16: "PS",
  17: "Touchpad",
  18: "L-Stick (X)",
  19: "L-Stick (Y)",
  20: "R-Stick (X)",
  21: "R-Stick (Y)",
  99: "Void",
};

// Legacy export name kept for macro export compatibility
export const SwitchControlLibrary: { [key: number]: string } = {
  0: "CIRCLE",
  1: "CROSS",
  2: "TRIANGLE",
  3: "SQUARE",
  4: "L1",
  5: "R1",
  6: "L2",
  7: "R2",
  8: "CREATE",
  9: "OPTIONS",
  10: "L3",
  11: "R3",
  12: "UP",
  13: "DOWN",
  14: "LEFT",
  15: "RIGHT",
  16: "PS",
  17: "TOUCHPAD",
  18: "L-Stick (X)",
  19: "L-Stick (Y)",
  20: "R-Stick (X)",
  21: "R-Stick (Y)",
  99: "Void",
};
