static const char *INDEX_HTML =
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no'>"
"<title>Ghostpad Bridge Controller</title>"
"<link rel='preconnect' href='https://fonts.googleapis.com'>"
"<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>"
"<link href='https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=JetBrains+Mono:wght@400;700&display=swap' rel='stylesheet'>"
"<style>"
"/*\n"
"  +-----------------------------------------+\n"
"  |              C S S   U I                |\n"
"  +-----------------------------------------+\n"
"*/\n"
"*{margin:0;padding:0;box-sizing:border-box;user-select:none;-webkit-user-select:none;font-family:'Outfit',sans-serif;}"
"body{background:linear-gradient(135deg,#f8fafc 0%,#e2e8f0 100%);color:#1e293b;height:100dvh;overflow:hidden;touch-action:none;}"
".page{display:none;height:100%;flex-direction:column;padding:16px;overflow-y:auto;}"
".page.active{display:flex;}"
".glass-panel{background:rgba(255,255,255,0.75);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);border:1px solid rgba(15,23,42,0.06);border-radius:16px;box-shadow:0 8px 30px rgba(0,0,0,0.04),0 1px 3px rgba(0,0,0,0.02);padding:16px;margin-bottom:12px;}"
".header{text-align:center;margin-bottom:16px;position:relative;}"
".header h1{font-size:24px;font-weight:800;background:linear-gradient(135deg,#1e3a8a 0%,#3b82f6 100%);-webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:1px;}"
".header .sub{font-size:12px;color:#64748b;margin-top:4px;font-family:'JetBrains Mono',monospace;font-weight:600;letter-spacing:0.5px;}"
".btn-primary{background:linear-gradient(135deg,#3b82f6 0%,#1d4ed8 100%);color:#fff;border:none;border-radius:12px;padding:14px;font-size:15px;font-weight:600;cursor:pointer;width:100%;transition:all .2s;box-shadow:0 4px 12px rgba(59,130,246,0.25);}"
".btn-primary:active{transform:scale(0.98);box-shadow:0 2px 6px rgba(59,130,246,0.15);}"
".btn-secondary{background:#ffffff;color:#475569;border:1px solid #cbd5e1;border-radius:12px;padding:10px;font-size:13px;font-weight:600;cursor:pointer;transition:all .2s;box-shadow:0 1px 2px rgba(0,0,0,0.03);}"
".btn-secondary:active{background:#f8fafc;border-color:#94a3b8;}"
".form-control{background:#ffffff;border:1px solid #cbd5e1;border-radius:12px;padding:12px 14px;color:#0f172a;font-size:14px;outline:none;font-family:'JetBrains Mono',monospace;transition:border-color 0.2s,box-shadow 0.2s;width:100%;}"
".form-control:focus{border-color:#3b82f6;box-shadow:0 0 0 3px rgba(59,130,246,0.1);}"
".device-card{background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;padding:14px;margin-bottom:10px;display:flex;align-items:center;gap:14px;cursor:pointer;transition:all 0.2s;box-shadow:0 1px 3px rgba(0,0,0,0.01);}"
".device-card:active{border-color:#3b82f6;background:rgba(59,130,246,0.04);}"
".device-card .icon{width:44px;height:44px;border-radius:10px;background:#f1f5f9;display:flex;align-items:center;justify-content:center;font-size:22px;border:1px solid #e2e8f0;}"
".device-card .info{flex:1;}"
".device-card .name{font-size:15px;font-weight:600;color:#0f172a;}"
".device-card .desc{font-size:11px;color:#64748b;margin-top:2px;font-family:'JetBrains Mono',monospace;}"
".status-dot{width:12px;height:12px;border-radius:50%;position:relative;}"
".status-dot.online{background:#10b981;box-shadow:0 0 8px rgba(16,185,129,0.5);}"
".status-dot.offline{background:#94a3b8;}"
".status-dot.pairing{background:#f59e0b;box-shadow:0 0 8px rgba(245,158,11,0.5);}"
".ble-section .ble-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px;}"
".ble-section .ble-title{font-size:13px;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:1px;}"
".ble-badge{font-size:11px;font-family:'JetBrains Mono',monospace;padding:3px 10px;border-radius:20px;font-weight:700;}"
".ble-badge.idle{background:#f1f5f9;color:#64748b;border:1px solid #e2e8f0;}"
".ble-badge.scanning{background:rgba(59,130,246,0.1);color:#2563eb;border:1px solid rgba(59,130,246,0.2);animation:pulse 1s infinite;}"
".ble-badge.connected{background:rgba(16,185,129,0.1);color:#059669;border:1px solid rgba(16,185,129,0.2);}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.5}}"
".ble-device-card{background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;padding:12px 14px;margin-bottom:8px;display:flex;align-items:center;gap:12px;box-shadow:0 1px 2px rgba(0,0,0,0.01);}"
".ble-device-card .ble-info{flex:1;}"
".ble-device-card .ble-name{font-size:14px;font-weight:600;color:#0f172a;}"
".ble-device-card .ble-addr{font-size:10px;color:#64748b;font-family:'JetBrains Mono',monospace;margin-top:2px;}"
".ble-device-card .ble-rssi{font-size:10px;color:#64748b;font-family:'JetBrains Mono',monospace;margin-left:4px;}"
".btn-ble-connect{background:linear-gradient(135deg,#3b82f6,#2563eb);color:#fff;border:none;border-radius:8px;padding:7px 14px;font-size:12px;font-weight:700;cursor:pointer;white-space:nowrap;transition:all 0.15s;box-shadow:0 2px 6px rgba(59,130,246,0.15);}"
".btn-ble-connect:active{transform:scale(0.97);}"
".btn-ble-disconnect{background:rgba(239,68,68,0.08);color:#ef4444;border:1px solid rgba(239,68,68,0.2);border-radius:8px;padding:7px 14px;font-size:12px;font-weight:700;cursor:pointer;white-space:nowrap;transition:all 0.15s;}"
".btn-ble-disconnect:active{background:rgba(239,68,68,0.15);}"
".ctrl-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;}"
".ctrl-top .back{background:#ffffff;border:1px solid #cbd5e1;color:#334155;border-radius:8px;padding:8px 16px;font-size:13px;font-weight:600;cursor:pointer;box-shadow:0 1px 2px rgba(0,0,0,0.03);transition:all 0.2s;}"
".ctrl-top .back:active{background:#f8fafc;}"
".ctrl-top .name{font-size:16px;font-weight:700;color:#1e3a8a;}"
".ctrl-container{flex:1;display:flex;flex-direction:column;justify-content:space-between;min-height:0;}"
".ctrl-row{display:flex;flex-direction:row;justify-content:space-around;align-items:center;margin:10px 0;}"
".ctrl-col{display:flex;flex-direction:column;align-items:center;gap:12px;}"
".joystick{width:130px;height:130px;border-radius:50%;background:radial-gradient(circle,#ffffff 0%,#e2e8f0 100%);border:2px solid #cbd5e1;position:relative;touch-action:none;box-shadow:inset 0 2px 6px rgba(0,0,0,0.06),0 2px 8px rgba(0,0,0,0.03);transition:border-color 0.2s;}"
".joystick.active{border-color:#3b82f6;}"
".joystick .knob{width:44px;height:44px;border-radius:50%;background:radial-gradient(circle,#64748b,#334155);position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);pointer-events:none;box-shadow:0 4px 10px rgba(51,65,85,0.3);}"
".btn-grid{display:grid;gap:6px;}"
".dpad{grid-template-columns:repeat(3,46px);}"
".face{grid-template-columns:repeat(3,46px);}"
".btn-grid button{height:44px;border:none;border-radius:10px;background:#ffffff;border:1px solid #cbd5e1;color:#334155;font-size:16px;cursor:pointer;touch-action:none;transition:all 0.15s;box-shadow:0 1px 2px rgba(0,0,0,0.02);}"
".btn-grid button:active,.btn-grid button.active{background:#3b82f6 !important;border-color:#2563eb !important;color:#ffffff !important;box-shadow:0 0 12px rgba(59,130,246,0.4);transform:scale(0.95);transition:none !important;}"
".btn-grid .empty{visibility:hidden;}"
".face button{border-radius:50%;background:#ffffff;font-weight:bold;}"
".ctrl-bar{display:flex;gap:6px;margin:6px 0;width:100%;justify-content:center;}"
".ctrl-bar button{height:36px;flex:1;max-width:90px;border:none;border-radius:8px;background:#ffffff;border:1px solid #cbd5e1;color:#334155;font-size:12px;font-weight:600;cursor:pointer;touch-action:none;transition:all 0.15s;box-shadow:0 1px 2px rgba(0,0,0,0.02);}"
".ctrl-bar button:active,.ctrl-bar button.active{background:#3b82f6 !important;color:#ffffff !important;border-color:#2563eb !important;box-shadow:0 0 12px rgba(59,130,246,0.4);transition:none !important;}"
".trig-row{display:flex;gap:16px;margin:8px 0;justify-content:center;width:100%;}"
".trig-row label{font-size:12px;color:#475569;display:flex;align-items:center;gap:8px;flex:1;max-width:160px;font-weight:600;}"
".trig-row input[type='range']{-webkit-appearance:none;width:100%;height:6px;border-radius:3px;background:#cbd5e1;outline:none;}"
".trig-row input[type='range']::-webkit-slider-thumb{-webkit-appearance:none;width:16px;height:16px;border-radius:50%;background:#3b82f6;cursor:pointer;box-shadow:0 2px 6px rgba(59,130,246,0.3);}"
".status-card{display:flex;align-items:center;justify-content:space-between;background:rgba(59,130,246,0.05);border:1px solid rgba(59,130,246,0.12);border-radius:12px;padding:10px 14px;margin-bottom:12px;}"
".status-card .status-title{font-size:12px;color:#475569;font-weight:700;letter-spacing:0.5px;}"
".status-card .status-value{font-size:13px;color:#2563eb;font-weight:bold;font-family:'JetBrains Mono',monospace;}"
"@media(max-height:600px){.joystick{width:90px;height:90px}.joystick .knob{width:32px;height:32px}.btn-grid button{height:36px;font-size:12px}.dpad,.face{grid-template-columns:repeat(3,38px)}}"
"</style>"
"</head>"
"<body>"
"<!--\n"
"  +-----------------------------------------+\n"
"  |             H T M L   U I               |\n"
"  +-----------------------------------------+\n"
"-->\n"
"<!-- PAGE: Device Browser -->"
"<div id='pageBrowser' class='page active'>"
"<div class='header'><h1>Ghostpad <span style='color:#3b82f6'>Bridge</span></h1><div class='sub'>HACK THE GAMEPAD BOUNDARIES</div></div>"
"<div class='status-card'>"
"<span class='status-title'>CONNECTED CONSOLE</span>"
"<span class='status-value' id='usbConsoleName'>None</span>"
"</div>"
"<!-- Manual Console IP -->"
"<div class='glass-panel'>"
"<div style='display:flex;font-size:13px;color:#475569;margin-bottom:8px;font-weight:700;letter-spacing:0.5px'><span>🔌 Direct Console Connection</span></div>"
"<div style='display:flex;gap:8px'>"
"<input type='text' id='manualIp' placeholder='PS4 IP (e.g. 192.168.1.50)' class='form-control' style='flex:1'>"
"<button class='btn-primary' style='flex:0 0 auto;padding:12px 20px;width:auto' onclick='connectManualIp()'>Connect</button>"
"</div>"
"</div>"
"<!-- BLE Controller Section -->"
"<div class='glass-panel ble-section' id='bleSectionPanel'>"
"<div class='ble-header'>"
"<span class='ble-title'>🎮 BT Controller</span>"
"<span class='ble-badge idle' id='bleBadge'>IDLE</span>"
"</div>"
"<div id='bleConnectedCard' style='display:none;margin-bottom:10px'></div>"
"<button class='btn-primary' id='bleScanBtn' onclick='startBleScan()' style='background:linear-gradient(135deg,#3b82f6 0%,#1d4ed8 100%);box-shadow:0 4px 15px rgba(59,130,246,0.2);margin-bottom:10px'>🔍 Scan BT Controllers</button>"
"<div id='bleDeviceList'></div>"
"</div>"
"<div class='glass-panel'>"
"<button class='btn-primary' id='scanBtn' onclick='scanDevices()' style='margin-bottom:0'>📡 Subnet Console Scan</button>"
"</div>"
"<div style='display:flex;gap:10px;margin-bottom:12px'>"
"<button class='btn-secondary' style='flex:1' onclick='showPage(\"pageSettings\")'>⚙ Settings</button>"
"<button class='btn-secondary' style='flex:1' onclick='showPage(\"pageKlog\")'>📋 Klog</button>"
"<button class='btn-secondary' style='flex:1' onclick='showPage(\"pageAbout\")'>ℹ About</button>"
"</div>"
"<div class='device-list' id='deviceList'>"
"<div class='device-card' onclick='selectedConsoleIp=\"usb\";document.getElementById(\"ctrlDeviceName\").textContent=\"PlayStation (USB)\";showPage(\"pageController\");'>"
"<div class='icon'>🔗</div>"
"<div class='info'>"
"<div class='name'>PlayStation (USB HID)</div>"
"<div class='desc'>Controlla la console connessa via USB</div>"
"</div>"
"<div class='status-dot offline' id='usbStatusDot'></div>"
"</div>"
"</div>"
"</div>"
"<!-- PAGE: Controller -->"
"<div id='pageController' class='page'>"
"<div class='ctrl-top'>"
"<button class='back' onclick='showPage(\"pageBrowser\")'>← Back</button>"
"<span class='name' id='ctrlDeviceName'>Virtual Controller</span>"
"<span id='ctrlStatus' style=\"font-size:11px;color:#2563eb;font-weight:bold;font-family:'JetBrains Mono',monospace\">○ Ready</span>"
"</div>"
"<div class='status-card' id='gamepadStatusCard' style='display:none;background:rgba(59,130,246,0.05);border-color:rgba(59,130,246,0.12)'>"
"<span class='status-title' style='color:#475569'>PHYSICAL GAMEPAD</span>"
"<span class='status-value' id='connectedGamepadName' style='color:#2563eb'>None</span>"
"</div>"
"<div class='status-card' id='esp32GamepadStatusCard' style='display:none;background:rgba(16,185,129,0.05);border-color:rgba(16,185,129,0.12)'>"
"<span class='status-title' style='color:#475569'>ESP32 BT CONTROLLER</span>"
"<span class='status-value' id='esp32GamepadName' style='color:#059669'>None</span>"
"</div>"
"<div class='ctrl-container'>"
"<div class='ctrl-row'>"
"<div class='ctrl-col'>"
"<div class='joystick' id='joyL'><div class='knob' id='knobL'></div></div>"
"<div class='btn-grid dpad'>"
"<button class='empty'></button><button data-btn='up'>▲</button><button class='empty'></button>"
"<button data-btn='left'>◀</button><button data-btn='down'>▼</button><button data-btn='right'>▶</button>"
"</div>"
"</div>"
"<div class='ctrl-col'>"
"<div class='joystick' id='joyR'><div class='knob' id='knobR'></div></div>"
"<div class='btn-grid face'>"
"<button class='empty'></button><button data-btn='triangle' style='color:#0d9488'>▲</button><button class='empty'></button>"
"<button data-btn='square' style='color:#db2777'>■</button><button data-btn='cross' style='color:#2563eb'>✕</button><button data-btn='circle' style='color:#ea580c'>●</button>"
"</div>"
"</div>"
"</div>"
"<div>"
"<div class='ctrl-bar'>"
"<button data-btn='l1'>L1</button><button data-btn='l2'>L2</button><button data-btn='l3'>L3</button>"
"<button data-btn='r1'>R1</button><button data-btn='r2'>R2</button><button data-btn='r3'>R3</button>"
"</div>"
"<div class='ctrl-bar'>"
"<button data-btn='create'>Create</button><button data-btn='options'>Opt</button>"
"<button data-btn='ps' style='border-color:#3b82f6;color:#2563eb'>PS</button><button data-btn='touchpad'>Touch</button>"
"</div>"
"<div class='trig-row'>"
"<label>L2 <input type='range' id='l2val' min='0' max='255' value='0'></label>"
"<label>R2 <input type='range' id='r2val' min='0' max='255' value='0'></label>"
"</div>"
"</div>"
"</div>"
"</div>"
"<!-- PAGE: Settings -->"
"<div id='pageSettings' class='page'>"
"<div class='ctrl-top'><button class='back' onclick='showPage(\"pageBrowser\")'>← Back</button><span class='name'>Settings</span><span></span></div>"
"<div class='glass-panel'>"
"<div style='font-size:13px;color:#475569;margin-bottom:8px;font-weight:600'>ESP32 System Status</div>"
"<div id='espStatus' style=\"font-size:12px;color:#334155;line-height:1.8;font-family:'JetBrains Mono',monospace\">Loading...</div>"
"</div>"
"<div class='glass-panel'>"
"<div style='font-size:13px;color:#475569;margin-bottom:8px;font-weight:600'>USB Console Interface</div>"
"<div id='usbStatus' style=\"font-size:12px;color:#334155;line-height:1.8;font-family:'JetBrains Mono',monospace\">Checking...</div>"
"</div>"
"<div class='glass-panel'>"
"<div style='font-size:13px;color:#475569;margin-bottom:8px;font-weight:600'>💾 Payload Manager</div>"
"<div id='payloadStatus' style=\"font-size:12px;color:#334155;line-height:1.8;font-family:'JetBrains Mono',monospace;margin-bottom:10px\">No payload loaded</div>"
"<input type='file' id='payloadFile' style='display:none' onchange='uploadPayload(this)'>"
"<button class='btn-secondary' style='width:100%;margin-bottom:10px' onclick='document.getElementById(\"payloadFile\").click()'>📤 Upload Payload</button>"
"<div style='display:flex;gap:8px;margin-bottom:8px'>"
"<input type='text' id='targetIp' placeholder='Console IP (e.g. 10.0.0.x)' class='form-control' style='flex:1'>"
"</div>"
"<div style='display:flex;gap:8px;margin-bottom:8px'>"
"<input type='number' id='targetPort' value='9021' min='1' max='65535' class='form-control' style='flex:0 0 auto;width:120px'>"
"<button class='btn-primary' style='flex:1;padding:12px 18px' onclick='deployPayload()'>🚀 Deploy</button>"
"</div>"
"<div id='deployLog' style=\"font-size:11px;color:#475569;line-height:1.6;font-family:'JetBrains Mono',monospace\"></div>"
"</div>"
"</div>"
"<!-- PAGE: About -->"
"<div id='pageAbout' class='page'>"
"<div class='ctrl-top'><button class='back' onclick='showPage(\"pageBrowser\")'>← Back</button><span class='name'>About</span><span></span></div>"
"<div class='glass-panel' style='text-align:center;padding:24px;color:#475569;font-size:14px;line-height:1.8'>"
"<h2 style='color:#2563eb;margin-bottom:14px;font-weight:800'>Ghostpad Bridge</h2>"
"<p>High performance custom ESP32-P4 and ESP32-C6 SDIO Wi-Fi co-processor system.</p>"
"<p style='margin-top:12px'>Connected directly via USB TinyUSB stack to act as a hardware-spoofed game controller.</p>"
"<p style=\"margin-top:16px;font-size:11px;font-family:'JetBrains Mono',monospace\">v1.1 · Waveshare P4 Board</p>"
"</div>"
"</div>"
"<!-- PAGE: Klog Viewer -->"
"<div id='pageKlog' class='page'>"
"<div class='ctrl-top'><button class='back' onclick='showPage(\"pageSettings\")'>← Back</button><span class='name'>📋 Klog Viewer</span><span></span></div>"
"<div class='glass-panel'>"
"<div style='display:flex;gap:8px;margin-bottom:10px'>"
"<input type='text' id='klogIp' placeholder='Console IP' class='form-control' style='flex:1'>"
"<button class='btn-primary' id='klogConnectBtn' style='flex:0 0 auto;padding:12px 18px;width:auto' onclick='klogConnect()'>🔌 Connect</button>"
"<button class='btn-secondary' id='klogDisconnectBtn' style='flex:0 0 auto;padding:12px 18px;width:auto;display:none' onclick='klogDisconnect()'>⛔ Disconnect</button>"
"</div>"
"<div id='klogStatus' style='font-size:11px;color:#475569;margin-bottom:8px;font-family:\"JetBrains Mono\",monospace'>Disconnected</div>"
"<div style='display:flex;gap:8px;margin-bottom:8px'>"
"<button class='btn-secondary' style='flex:0 0 auto;padding:6px 14px;font-size:12px' onclick='klogCopy()'>📋 Copy</button>"
"<button class='btn-secondary' style='flex:0 0 auto;padding:6px 14px;font-size:12px' onclick='klogClear()'>🗑 Clear</button>"
"<label style='margin-left:auto;font-size:12px;color:#475569;display:flex;align-items:center;gap:4px'><input type='checkbox' id='klogAutoScroll' checked onchange=''>Auto-scroll</label>"
"</div>"
"<pre id='klogOutput' style='background:#0f172a;border:1px solid #1e293b;border-radius:8px;padding:12px;height:50vh;overflow-y:auto;font-family:\"JetBrains Mono\",monospace;font-size:11px;line-height:1.5;color:#38bdf8;white-space:pre-wrap;word-break:break-all;box-shadow:inset 0 2px 4px rgba(0,0,0,0.2)'>Waiting for klog data...</pre>"
"</div>"
"</div>"
"<script>"
"/*\n"
"  +-----------------------------------------+\n"
"  |       J A V A S C R I P T   L O G I C   |\n"
"  +-----------------------------------------+\n"
"*/\n"
"const BTN_MAP={"
"cross:1,square:2,circle:4,triangle:8,"
"up:16,right:32,down:64,left:128,"
"l1:256,r1:512,l3:1024,r3:2048,"
"l2:4096,r2:8192,ps:16384,create:32768,"
"options:65536,touchpad:131072"
"};"
"let state={buttons:0,lx:128,ly:128,rx:128,ry:128,l2:0,r2:0};"
"let ws=null;let wsReconnect=null;let activeGamepadIndex=null;let loopId=null;let scanInterval=null;let selectedConsoleIp=null;let controllerStreamTimer=null;let controllerActive=false;let controllerSeq=0;let lastSendAt=0;let lastStateStr='';"
"function showPage(id){"
"document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));"
"document.getElementById(id).classList.add('active');"
"if(id==='pageBrowser'){stopControllerConnection();refreshDevices();startBrowserPoll();}"
"else if(id==='pageController'){stopBrowserPoll();connectWs();startGamepadLoop();startControllerStream();}"
"else {stopBrowserPoll();stopControllerConnection();}"
"if(id==='pageSettings'){refreshSettings();refreshPayloadStatus();}"
"}"
"function setCtrlStatus(text,color){"
"const el=document.getElementById('ctrlStatus');"
"if(el){"
"el.textContent=text;"
"if(color==='#ffab00') color='#d97706';"
"else if(color==='#00f5d4') color='#16a34a';"
"else if(color==='#e94560') color='#dc2626';"
"el.style.color=color||'#475569';"
"}"
"}"
"function openControllerFor(ip,name){selectedConsoleIp=ip;document.getElementById('ctrlDeviceName').textContent=name||'PlayStation (Wi-Fi)';document.getElementById('targetIp').value=ip;showPage('pageController');}"
"function connectWs(){"
"if(!selectedConsoleIp){setCtrlStatus('! No target','#d97706');return;}"
"if(ws&&(ws.readyState===WebSocket.OPEN||ws.readyState===WebSocket.CONNECTING))return;"
"const p=location.protocol==='https:'?'wss:':'ws:';"
"const u=p+'//'+location.host+'/ws';"
"setCtrlStatus('○ Connecting','#d97706');"
"ws=new WebSocket(u);"
"ws.onopen=()=>{controllerActive=true;setCtrlStatus('● Streaming','#16a34a');ws.send(JSON.stringify({target_ip:selectedConsoleIp,hello:'controller'}));sendState(true);startControllerStream();};"
"ws.onmessage=(e)=>{try{const msg=JSON.parse(e.data);if(msg.event==='console_connected')setCtrlStatus('● GPAD '+msg.ip,'#16a34a');else if(msg.event==='console_error')setCtrlStatus('! '+msg.msg,'#dc2626');else if(msg.event==='gamepad_state'){for(const btn in BTN_MAP){const press=(msg.buttons&BTN_MAP[btn])!==0;visualPress(btn,press);}const l2=getEl('l2val'),r2=getEl('r2val');if(l2)l2.value=msg.l2;if(r2)r2.value=msg.r2;updateJoystickVisual('knobL',(msg.lx-128)/128,(msg.ly-128)/128);updateJoystickVisual('knobR',(msg.rx-128)/128,(msg.ry-128)/128);const ec=getEl('esp32GamepadStatusCard'),en=getEl('esp32GamepadName');if(ec&&en){if(msg.bt_connected){en.textContent=msg.bt_name||'Controller';ec.style.display='flex';}else{ec.style.display='none';}}}}catch(_){}};"
"ws.onclose=()=>{setCtrlStatus('○ Closed','#dc2626');ws=null;stopControllerStream();if(controllerActive&&document.getElementById('pageController').classList.contains('active')){clearTimeout(wsReconnect);wsReconnect=setTimeout(connectWs,1500);}};"
"ws.onerror=()=>{setCtrlStatus('! WS error','#dc2626');ws&&ws.close();};"
"}"
"function startControllerStream(){"
"if(controllerStreamTimer)return;"
"controllerActive=true;"
"controllerStreamTimer=setInterval(()=>sendState(false),33);"
"}"
"function stopControllerStream(){"
"if(controllerStreamTimer){clearInterval(controllerStreamTimer);controllerStreamTimer=null;}"
"}"
"function stopControllerConnection(){"
"controllerActive=false;"
"stopControllerStream();"
"stopGamepadLoop();"
"if(ws){ws.onclose=null;try{sendNeutralState();}catch(_){ }try{ws.close();}catch(_){ }ws=null;}"
"clearTimeout(wsReconnect);wsReconnect=null;"
"}"
"function sendNeutralState(){"
"const old={...state};"
"state.buttons=0;state.lx=128;state.ly=128;state.rx=128;state.ry=128;state.l2=0;state.r2=0;"
"sendState(true);"
"state=old;"
"}"
"function sendState(force){"
"if(!ws||ws.readyState!==WebSocket.OPEN)return;"
"const now=Date.now();"
"if(!force&&now-lastSendAt<20)return;"
"const stateStr=JSON.stringify({s:state,ip:selectedConsoleIp});"
"if(!force&&stateStr===lastStateStr)return;"
"lastStateStr=stateStr;"
"lastSendAt=now;"
"controllerSeq=(controllerSeq+1)>>>0;"
"ws.send(JSON.stringify({...state,target_ip:selectedConsoleIp,seq:controllerSeq,ts:now}));"
"}"
"function updateBtn(btn,press){"
"const bits=BTN_MAP[btn];"
"if(!bits)return;"
"const el=document.querySelector(`[data-btn='${btn}']`);"
"if(press){"
"state.buttons|=bits;"
"if(el)el.classList.add('active');"
"}else{"
"state.buttons&=~bits;"
"if(el)el.classList.remove('active');"
"}"
"sendState();"
"}"
"function setupJoy(id,ox,oy,knobId){"
"const el=document.getElementById(id);"
"const knob=document.getElementById(knobId);"
"let active=false;"
"function mv(e){"
"if(!active)return;"
"const t=e.touches?e.touches[0]:e;"
"const r=el.getBoundingClientRect();"
"const cx=r.left+r.width/2,cy=r.top+r.height/2;"
"const mr=r.width/2-22;"
"let dx=t.clientX-cx,dy=t.clientY-cy;"
"const d=Math.sqrt(dx*dx+dy*dy);"
"if(d>mr){dx=dx/d*mr;dy=dy/d*mr;}"
"knob.style.left=(50+dx/mr*40)+'%';"
"knob.style.top=(50+dy/mr*40)+'%';"
"state[ox]=Math.round(128+dx/mr*127);"
"state[oy]=Math.round(128+dy/mr*127);"
"sendState();"
"}"
"function st(e){active=true;el.classList.add('active');mv(e);}"
"function en(){"
"if(!active)return;"
"active=false;el.classList.remove('active');knob.style.left='50%';knob.style.top='50%';"
"state[ox]=128;state[oy]=128;sendState();"
"}"
"el.addEventListener('touchstart',st,{passive:true});"
"el.addEventListener('touchmove',mv,{passive:true});"
"el.addEventListener('touchend',en);el.addEventListener('touchcancel',en);"
"el.addEventListener('mousedown',st);"
"window.addEventListener('mousemove',mv);window.addEventListener('mouseup',en);"
"}"
"function connectManualIp(){"
"const ip=document.getElementById('manualIp').value.trim();"
"if(!ip){"
"document.getElementById('manualIp').style.borderColor='#dc2626';"
"setTimeout(()=>{document.getElementById('manualIp').style.borderColor='#cbd5e1'},1000);"
"return;"
"}"
"selectedConsoleIp=ip;"
"document.getElementById('ctrlDeviceName').textContent='PlayStation ('+ip+')';"
"showPage('pageController');"
"}"
"setupJoy('joyL','lx','ly','knobL');"
"setupJoy('joyR','rx','ry','knobR');"
"document.querySelectorAll('[data-btn]').forEach(b=>{"
"const btn=b.dataset.btn;"
"b.addEventListener('touchstart',e=>{e.preventDefault();updateBtn(btn,true);},{passive:false});"
"b.addEventListener('touchend',e=>{e.preventDefault();updateBtn(btn,false);});"
"b.addEventListener('touchcancel',e=>{updateBtn(btn,false);});"
"b.addEventListener('mousedown',e=>{updateBtn(btn,true);});"
"b.addEventListener('mouseup',e=>{updateBtn(btn,false);});"
"b.addEventListener('mouseleave',e=>{updateBtn(btn,false);});"
"});"
"document.getElementById('l2val').addEventListener('input',function(){state.l2=parseInt(this.value);sendState();});"
"document.getElementById('r2val').addEventListener('input',function(){state.r2=parseInt(this.value);sendState();});"
"window.addEventListener('gamepadconnected',(e)=>{console.log('Gamepad connected:',e.gamepad.id);activeGamepadIndex=e.gamepad.index;updateGamepadStatus(e.gamepad);});"
"window.addEventListener('gamepaddisconnected',(e)=>{console.log('Gamepad disconnected:',e.gamepad.id);if(activeGamepadIndex===e.gamepad.index){activeGamepadIndex=null;updateGamepadStatus(null);}});"
"function updateGamepadStatus(gp){"
"const card=document.getElementById('gamepadStatusCard');"
"const nameLabel=document.getElementById('connectedGamepadName');"
"if(gp){"
"nameLabel.textContent=gp.id.split('(')[0].trim();"
"card.style.display='flex';"
"}else{"
"card.style.display='none';"
"}"
"}"
"function pollGamepad(){"
"if(activeGamepadIndex===null)return;"
"const gp=navigator.getGamepads()[activeGamepadIndex];"
"if(!gp)return;"
"state.lx=Math.round(128+gp.axes[0]*127);"
"state.ly=Math.round(128+gp.axes[1]*127);"
"state.rx=Math.round(128+gp.axes[2]*127);"
"state.ry=Math.round(128+gp.axes[3]*127);"
"updateJoystickVisual('knobL',gp.axes[0],gp.axes[1]);"
"updateJoystickVisual('knobR',gp.axes[2],gp.axes[3]);"
"let buttons=0;"
"if(gp.buttons[0].pressed){buttons|=BTN_MAP.cross;visualPress('cross',true);}else{visualPress('cross',false);}"
"if(gp.buttons[1].pressed){buttons|=BTN_MAP.circle;visualPress('circle',true);}else{visualPress('circle',false);}"
"if(gp.buttons[2].pressed){buttons|=BTN_MAP.square;visualPress('square',true);}else{visualPress('square',false);}"
"if(gp.buttons[3].pressed){buttons|=BTN_MAP.triangle;visualPress('triangle',true);}else{visualPress('triangle',false);}"
"if(gp.buttons[4].pressed){buttons|=BTN_MAP.l1;visualPress('l1',true);}else{visualPress('l1',false);}"
"if(gp.buttons[5].pressed){buttons|=BTN_MAP.r1;visualPress('r1',true);}else{visualPress('r1',false);}"
"if(gp.buttons[8].pressed){buttons|=BTN_MAP.create;visualPress('create',true);}else{visualPress('create',false);}"
"if(gp.buttons[9].pressed){buttons|=BTN_MAP.options;visualPress('options',true);}else{visualPress('options',false);}"
"if(gp.buttons[10].pressed){buttons|=BTN_MAP.l3;visualPress('l3',true);}else{visualPress('l3',false);}"
"if(gp.buttons[11].pressed){buttons|=BTN_MAP.r3;visualPress('r3',true);}else{visualPress('r3',false);}"
"if(gp.buttons[12].pressed){buttons|=BTN_MAP.up;visualPress('up',true);}else{visualPress('up',false);}"
"if(gp.buttons[13].pressed){buttons|=BTN_MAP.down;visualPress('down',true);}else{visualPress('down',false);}"
"if(gp.buttons[14].pressed){buttons|=BTN_MAP.left;visualPress('left',true);}else{visualPress('left',false);}"
"if(gp.buttons[15].pressed){buttons|=BTN_MAP.right;visualPress('right',true);}else{visualPress('right',false);}"
"if(gp.buttons[16]&&gp.buttons[16].pressed){buttons|=BTN_MAP.ps;visualPress('ps',true);}else{visualPress('ps',false);}"
"if(gp.buttons[17]&&gp.buttons[17].pressed){buttons|=BTN_MAP.touchpad;visualPress('touchpad',true);}else{visualPress('touchpad',false);}"
"state.l2=Math.round(gp.buttons[6].value*255);"
"state.r2=Math.round(gp.buttons[7].value*255);"
"const l2=getEl('l2val'),r2=getEl('r2val');if(l2)l2.value=state.l2;if(r2)r2.value=state.r2;"
"state.buttons=buttons;"
"sendState();"
"}"
"const elCache={};"
"function getEl(id){"
"let el=elCache[id];"
"if(!el){el=document.getElementById(id);if(el)elCache[id]=el;}"
"return el;"
"}"
"const btnCache={};"
"function visualPress(btn,press){"
"let el=btnCache[btn];"
"if(!el){el=document.querySelector(`[data-btn='${btn}']`);if(!el)return;btnCache[btn]=el;}"
"if(press)el.classList.add('active');"
"else el.classList.remove('active');"
"}"
"function updateJoystickVisual(knobId,x,y){"
"const knob=getEl(knobId);"
"if(knob){"
"knob.style.left=(50+x*40)+'%';"
"knob.style.top=(50+y*40)+'%';"
"}"
"}"
"function startGamepadLoop(){"
"if(loopId)return;"
"function l(){pollGamepad();loopId=requestAnimationFrame(l);}"
"loopId=requestAnimationFrame(l);"
"}"
"function stopGamepadLoop(){"
"if(loopId){cancelAnimationFrame(loopId);loopId=null;}"
"}"
"async function startBleScan(){"
"const btn=document.getElementById('bleScanBtn');"
"const badge=document.getElementById('bleBadge');"
"const list=document.getElementById('bleDeviceList');"
"btn.disabled=true;btn.textContent='⏳ Scanning...';"
"badge.className='ble-badge scanning';badge.textContent='SCANNING';"
"list.innerHTML='';"
"try{"
"const r=await fetch('/api/ble/scan');"
"const data=await r.json();"
"if(data.synced===false){"
"list.innerHTML='<div style=\"color:#d97706;font-size:12px;padding:10px 0\">⚠ BT Classic host not ready yet. Make sure this firmware is running on an original ESP32/WROOM/WROVER target, not ESP32-C3/C6/S3/P4.</div>';"
"}"
"else if(data.scan_ok===false){"
"list.innerHTML='<div style=\"color:#dc2626;font-size:12px;padding:10px 0\">✗ BT Classic scan failed: '+(data.error||'unknown')+'. The C6 BT controller may not be available.</div>';"
"}"
"else{"
"renderBleDevices(data.devices||[],data);"
"}"
"}catch(e){"
"list.innerHTML='<div style=\"color:#dc2626;font-size:12px;padding:10px 0\">Scan error: '+e.message+'</div>';"
"}"
"btn.disabled=false;btn.textContent='🔍 Scan BT Classic Controllers';"
"badge.className='ble-badge idle';badge.textContent='IDLE';"
"}"
"function renderBleDevices(list,data){"
"const el=document.getElementById('bleDeviceList');"
"el.innerHTML='';"
"if(data&&data.connected){"
"renderBleConnected(data.device_name,data.device_addr);"
"return;"
"}"
"if(!list||list.length===0){"
"el.innerHTML='<div style=\"color:#64748b;font-size:12px;text-align:center;padding:12px 0\">No Bluetooth Classic gamepads found. Put the controller in pairing mode and keep it close to the ESP32.</div>';"
"return;"
"}"
"list.forEach(d=>{"
"const card=document.createElement('div');"
"card.className='ble-device-card';"
"card.innerHTML='"
"<div class=\"ble-info\">"
"<div class=\"ble-name\">'+d.name+' <span class=\"ble-rssi\">'+d.rssi+'dBm</span></div>'"
"+'<div class=\"ble-addr\">'+d.addr+'</div></div>'"
"+'<button class=\"btn-ble-connect\" onclick=\"connectBle(\\''+d.addr+'\\',\\''+d.name+'\\')\" >Connect</button>'"
";"
"el.appendChild(card);"
"});"
"}"
"async function connectBle(addr,name){"
"const badge=document.getElementById('bleBadge');"
"badge.className='ble-badge scanning';badge.textContent='CONNECTING';"
"try{"
"const r=await fetch('/api/ble/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({addr})});"
"const data=await r.json();"
"if(data.ok){"
"renderBleConnected(name,addr);"
"}else{"
"badge.className='ble-badge idle';badge.textContent='FAILED';"
"}"
"}catch(e){"
"badge.className='ble-badge idle';badge.textContent='ERROR';"
"}"
"}"
"function renderBleConnected(name,addr){"
"const badge=document.getElementById('bleBadge');"
"badge.className='ble-badge connected';badge.textContent='CONNECTED';"
"const list=document.getElementById('bleDeviceList');"
"list.innerHTML='';"
"const cc=document.getElementById('bleConnectedCard');"
"cc.style.display='block';"
"cc.innerHTML='"
"<div class=\"ble-device-card\" style=\"border-color:rgba(16,185,129,0.25);background:rgba(16,185,129,0.04)\">"
"<div class=\"ble-info\"><div class=\"ble-name\">'+name+'</div><div class=\"ble-addr\">'+addr+'</div></div>'"
"+'<button class=\"btn-ble-disconnect\" onclick=\"disconnectBle()\">Disconnect</button>'"
"+'</div>';"
"}"
"async function disconnectBle(){"
"await fetch('/api/ble/disconnect',{method:'POST'});"
"document.getElementById('bleConnectedCard').style.display='none';"
"document.getElementById('bleDeviceList').innerHTML='';"
"const badge=document.getElementById('bleBadge');"
"badge.className='ble-badge idle';badge.textContent='IDLE';"
"}"
"async function refreshBleStatus(){"
"try{"
"const r=await fetch('/api/ble/status');"
"const data=await r.json();"
"if(data.connected){"
"renderBleConnected(data.device_name,data.device_addr);"
"}else{"
"const badge=document.getElementById('bleBadge');"
"if(badge.textContent==='CONNECTED'){"
"badge.className='ble-badge idle';badge.textContent='IDLE';"
"document.getElementById('bleConnectedCard').style.display='none';"
"}"
"}"
"}catch(e){}"
"}"
"async function scanDevices(){"
"const btn=document.getElementById('scanBtn');"
"btn.disabled=true;btn.textContent='Scanning...';"
"try{"
"const r=await fetch('/api/scan');"
"const data=await r.json();"
"renderDevices(data.devices);"
"}catch(e){"
"document.getElementById('deviceList').innerHTML='<div style=\"text-align:center;color:#dc2626;padding:40px 0;font-size:13px\">Scan failed: '+e.message+'</div>';"
"}"
"btn.disabled=false;btn.textContent='🔍 Subnet Console Scan';"
"}"
"async function refreshDevices(){"
"try{"
"const statusReq=await fetch('/api/status');"
"const statusData=await statusReq.json();"
"if(statusData.wifi_console&&statusData.wifi_console.connected){"
"document.getElementById('usbConsoleName').textContent='WiFi: '+statusData.wifi_console.ip;"
"}else{"
"document.getElementById('usbConsoleName').textContent=statusData.usb.device||'None';"
"}"
"const usbDot=document.getElementById('usbStatusDot');"
"if(usbDot){"
"if(statusData.usb.connected){"
"usbDot.className='status-dot online';"
"}else{"
"usbDot.className='status-dot offline';"
"}"
"}"
"const wfid='wifi-active-card';"
"let wcard=document.getElementById(wfid);"
"if(statusData.wifi_console&&statusData.wifi_console.connected){"
"if(!wcard){"
"wcard=document.createElement('div');"
"wcard.id=wfid;"
"wcard.className='device-card';"
"wcard.onclick=()=>openControllerFor(statusData.wifi_console.ip,'PlayStation (Wi-Fi)');"
"wcard.innerHTML=\'<div class=\"icon\">🎮</div><div class=\"info\"><div class=\"name\">PlayStation (Wi-Fi)</div><div class=\"desc\">\'+statusData.wifi_console.ip+\' | Connected</div></div><div class=\"status-dot online\"></div>\';"
"document.getElementById(\'deviceList\').appendChild(wcard);"
"}"
"}else{"
"if(wcard)wcard.remove();"
"}"
"}catch(e){}"
"}"
"function renderDevices(list){"
"const target=document.getElementById('deviceList');"
"target.innerHTML='';"
"const usbCard=document.createElement('div');"
"usbCard.className='device-card';"
"usbCard.onclick=()=>openControllerFor('usb','PlayStation (USB HID)');"
"usbCard.innerHTML='<div class=\"icon\">🔗</div><div class=\"info\"><div class=\"name\">PlayStation (USB HID)</div><div class=\"desc\">Controlla la console connessa via USB</div></div><div class=\"status-dot offline\" id=\"usbStatusDot\"></div>';"
"target.appendChild(usbCard);"
"if(list&&list.length>0){"
"list.forEach(d=>{"
"if(d.ip==='usb:0')return;"
"const card=document.createElement('div');"
"card.className='device-card';"
"const statusClass=d.status==='online'?'online':(d.status==='pairing'?'pairing':'offline');"
"const desc=d.desc||'';"
"const hasElf=desc.includes('ELF:✓');"
"const hasKlog=desc.includes('KLOG:✓');"
"const hasGpad=desc.includes('GPAD:✓');"
"const has9090=desc.includes('9090:✓');"
"card.innerHTML=''"
"+'<div class=\"icon\">'+(d.icon||'🎮')+'</div>'"
"+'<div class=\"info\"><div class=\"name\">'+d.name+'</div><div class=\"desc\">'+d.desc+'</div>'"
"+'<div style=\"display:flex;gap:4px;margin-top:6px\">'"
"+(hasElf?'<button class=\"btn-ble-connect\" style=\"width:auto;padding:4px 10px;font-size:10px\" onclick=\"event.stopPropagation();deployToConsole(\\''+d.ip+'\\',9021)\">ELF 9021</button>':'')"
"+(hasGpad?'<button class=\"btn-ble-connect\" style=\"width:auto;padding:4px 10px;font-size:10px;background:linear-gradient(135deg,#3b82f6,#2563eb)\" onclick=\"event.stopPropagation();openControllerFor(\\''+d.ip+'\\',\\''+(d.name||'PlayStation')+'\\')\">Control</button>':'')"
"+(hasKlog?'<button class=\"btn-ble-connect\" style=\"width:auto;padding:4px 10px;font-size:10px;background:linear-gradient(135deg,#f59e0b,#d97706)\" onclick=\"event.stopPropagation();openKlogFor(\\''+d.ip+'\\')\">Klog</button>':'')"
"+(has9090?'<button class=\"btn-ble-connect\" style=\"width:auto;padding:4px 10px;font-size:10px;background:linear-gradient(135deg,#8b5cf6,#6d28d9)\" onclick=\"event.stopPropagation();deployToConsole(\\''+d.ip+'\\',9090)\">9090</button>':'')"
"+'</div></div>'"
"+'<div class=\"status-dot '+statusClass+'\"></div>';"
"card.onclick=()=>openControllerFor(d.ip,d.name);"
"target.appendChild(card);"
"});"
"}"
"}"
"function startBrowserPoll(){"
"if(!scanInterval){scanInterval=setInterval(()=>{refreshDevices();refreshBleStatus();},5000);}"
"}"
"function stopBrowserPoll(){"
"if(scanInterval){clearInterval(scanInterval);scanInterval=null;}"
"}"
"async function uploadPayload(input){"
"const file=input.files[0];"
"if(!file)return;"
"const log=document.getElementById('deployLog');"
"log.innerHTML='Uploading '+file.name+' ('+file.size+' bytes)...';"
"try{"
"const r=await fetch('/api/payload',{method:'POST',body:file,headers:{'Content-Disposition':'filename=\"'+file.name+'\"'}});"
"const data=await r.json();"
"if(data.ok){"
"log.innerHTML='<span style=\"color:#16a34a\">✓ Payload uploaded: '+file.name+'</span>';"
"refreshPayloadStatus();"
"}else{"
"log.innerHTML='<span style=\"color:#dc2626\">✗ Upload failed</span>';"
"}"
"}catch(e){"
"log.innerHTML='<span style=\"color:#dc2626\">✗ Upload error: '+e.message+'</span>';"
"}"
"input.value='';"
"}"
"async function deployPayload(){"
"const ip=document.getElementById('targetIp').value.trim();"
"const port=parseInt(document.getElementById('targetPort').value)||9021;"
"const log=document.getElementById('deployLog');"
"if(!ip){log.innerHTML='<span style=\"color:#d97706\">⚠ Enter a console IP address</span>';return;}"
"log.innerHTML='<span style=\"color:#2563eb\">⟳ Deploying to '+ip+':'+port+'...</span>';"
"try{"
"const r=await fetch('/api/deploy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip:ip,port:port})});"
"const data=await r.json();"
"if(data.ok){"
"log.innerHTML='<span style=\"color:#16a34a\">✓ Deployed '+data.sent+'/'+data.total+' bytes to '+ip+':'+port+'</span>';"
"}else{"
"log.innerHTML='<span style=\"color:#dc2626\">✗ Deploy failed: '+(data.error||'unknown')+'</span>';"
"}"
"}catch(e){"
"log.innerHTML='<span style=\"color:#dc2626\">✗ Deploy error: '+e.message+'</span>';"
"}"
"}"
"async function deployToConsole(ip,port){"
"port=port||9021;"
"document.getElementById('targetIp').value=ip;"
"document.getElementById('targetPort').value=port;"
"const log=document.getElementById('deployLog');"
"log.innerHTML='<span style=\"color:#2563eb\">⟳ Deploying to '+ip+':'+port+'...</span>';"
"try{"
"const r=await fetch('/api/deploy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip:ip,port:port})});"
"const data=await r.json();"
"if(data.ok){"
"log.innerHTML='<span style=\"color:#16a34a\">✓ Deployed '+data.sent+'/'+data.total+' bytes to '+ip+':'+port+'</span>';"
"}else{"
"log.innerHTML='<span style=\"color:#dc2626\">✗ Deploy failed: '+(data.error||'unknown')+'</span>';"
"}"
"}catch(e){"
"log.innerHTML='<span style=\"color:#dc2626\">✗ Deploy error: '+e.message+'</span>';"
"}"
"}"
"async function refreshPayloadStatus(){"
"try{"
"const r=await fetch('/api/payload');"
"const data=await r.json();"
"const el=document.getElementById('payloadStatus');"
"if(data.loaded){"
"el.innerHTML='<span style=\"color:#16a34a\">✓ Loaded:</span> '+data.name+' <span style=\"color:#64748b\">('+data.size+' bytes)</span>';"
"}else{"
"el.innerHTML='<span style=\"color:#64748b\">○ No payload loaded</span>';"
"}"
"}catch(e){}"
"}"
"async function refreshSettings(){"
"try{"
"const r=await fetch('/api/status');"
"const data=await r.json();"
"document.getElementById('espStatus').innerHTML='<div>WiFi AP SSID: '+data.wifi_ssid+'</div><div>Local IP: '+data.ip+'</div><div>Connected Clients: '+data.clients+'</div><div>Uptime: '+data.uptime+'s</div>';"
"document.getElementById('usbStatus').innerHTML='<div>Emulated controller: '+(data.usb.device||'None')+'</div><div>Connected to Host: '+(data.usb.connected?'Yes':'No')+'</div>';"
"}catch(e){"
"document.getElementById('espStatus').textContent='Error loading status';"
"}"
"}"
"let klogWs=null;let klogBuf='';"
"function openKlogFor(ip){document.getElementById('klogIp').value=ip;showPage('pageKlog');setTimeout(klogConnect,150);}"
"function klogConnect(){"
"const ip=document.getElementById('klogIp').value.trim();\n"
"if(!ip){document.getElementById('klogStatus').textContent='! Enter a console IP';return}\n"
"klogDisconnect();\n"
"const proto=location.protocol==='https:'?'wss:':'ws:';\n"
"klogWs=new WebSocket(proto+'//'+location.host+'/ws/klog');\n"
"klogWs.onopen=()=>{\n"
"document.getElementById('klogStatus').textContent='. Connected to '+ip+':3232';\n"
"document.getElementById('klogConnectBtn').style.display='none';\n"
"document.getElementById('klogDisconnectBtn').style.display='inline-block';\n"
"document.getElementById('klogOutput').textContent='';klogBuf='';\n"
"klogWs.send(JSON.stringify({cmd:'connect',ip:ip}));\n"
"};\n"
"klogWs.onmessage=(e)=>{\n"
"const el=document.getElementById('klogOutput');\n"
"if(e.data instanceof Blob){\n"
"const reader=new FileReader();\n"
"reader.onload=()=>{klogAppend(reader.result)};\n"
"reader.readAsText(e.data);\n"
"}else{klogAppend(e.data)}\n"
"};\n"
"klogWs.onclose=()=>{klogCleanup();document.getElementById('klogStatus').textContent='x Disconnected'};\n"
"klogWs.onerror=()=>{klogCleanup();document.getElementById('klogStatus').textContent='x WebSocket error'};\n"
"}\n"
"function klogAppend(text){\n"
"klogBuf+=text;\n"
"const el=document.getElementById('klogOutput');\n"
"el.textContent=klogBuf;\n"
"if(document.getElementById('klogAutoScroll').checked){\n"
"el.scrollTop=el.scrollHeight\n"
"}\n"
"}\n"
"function klogDisconnect(){\n"
"if(klogWs){klogWs.send(JSON.stringify({cmd:'disconnect'}));klogWs.close();klogWs=null}\n"
"klogCleanup()\n"
"}\n"
"function klogCleanup(){\n"
"document.getElementById('klogConnectBtn').style.display='inline-block';\n"
"document.getElementById('klogDisconnectBtn').style.display='none';\n"
"document.getElementById('klogStatus').textContent='Disconnected';\n"
"if(klogWs){klogWs.onclose=null;klogWs.close();klogWs=null}\n"
"}\n"
"function klogCopy(){\n"
"if(klogBuf){\n"
"navigator.clipboard.writeText(klogBuf).catch(()=>{\n"
"const ta=document.createElement('textarea');ta.value=klogBuf;document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta)\n"
"});\n"
"}\n"
"}\n"
"function klogClear(){klogBuf='';document.getElementById('klogOutput').textContent=''}\n"
"window.addEventListener('beforeunload',()=>{try{sendNeutralState();}catch(_){}});\n"
"startBrowserPoll();\n"
"showPage('pageBrowser');\n"
"</script>"
"</body></html>";
