
static const char *INDEX_HTML =
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1,user-scalable=no'>"
"<title>Ghostpad Bridge Controller</title>"
"<link rel='preconnect' href='https://fonts.googleapis.com'>"
"<link rel='preconnect' href='https://fonts.gstatic.com' crossorigin>"
"<link href='https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=JetBrains+Mono:wght@400;700&display=swap' rel='stylesheet'>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box;user-select:none;-webkit-user-select:none;font-family:'Outfit',sans-serif;}"
"body{background:radial-gradient(circle at center, #0f0c22 0%, #05020c 100%);color:#f1f1f9;height:100dvh;overflow:hidden;touch-action:none;}"
".page{display:none;height:100%;flex-direction:column;padding:16px;overflow-y:auto;}"
".page.active{display:flex;}"
".glass-panel{background:rgba(18, 18, 42, 0.6);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px);border:1px solid rgba(255,255,255,0.08);border-radius:16px;box-shadow:0 8px 32px 0 rgba(0,0,0,0.4);padding:16px;margin-bottom:12px;}"
".header{text-align:center;margin-bottom:16px;position:relative;}"
".header h1{font-size:24px;font-weight:800;background:linear-gradient(to right, #00f5d4, #e94560);-webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:1px;}"
".header .sub{font-size:12px;color:#8a8a9e;margin-top:4px;font-family:'JetBrains Mono',monospace;}"
".btn-primary{background:linear-gradient(135deg,#e94560 0%,#ff2a5f 100%);color:#fff;border:none;border-radius:12px;padding:14px;font-size:15px;font-weight:600;cursor:pointer;width:100%;transition:all .2s;box-shadow:0 4px 15px rgba(233,69,96,0.3);}"
".btn-primary:active{transform:scale(0.98);box-shadow:0 2px 8px rgba(233,69,96,0.2);}"
".btn-secondary{background:rgba(255,255,255,0.05);color:#f1f1f9;border:1px solid rgba(255,255,255,0.1);border-radius:12px;padding:10px;font-size:13px;font-weight:600;cursor:pointer;transition:all .2s;}"
".btn-secondary:active{background:rgba(255,255,255,0.1);}"
".device-card{background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.05);border-radius:12px;padding:14px;margin-bottom:10px;display:flex;align-items:center;gap:14px;cursor:pointer;transition:all 0.2s;}"
".device-card:active{border-color:#e94560;background:rgba(233,69,96,0.05);}"
".device-card .icon{width:44px;height:44px;border-radius:10px;background:rgba(0,0,0,0.3);display:flex;align-items:center;justify-content:center;font-size:22px;border:1px solid rgba(255,255,255,0.05);}"
".device-card .info{flex:1;}"
".device-card .name{font-size:15px;font-weight:600;color:#fff;}"
".device-card .desc{font-size:11px;color:#8a8a9e;margin-top:2px;font-family:'JetBrains Mono',monospace;}"
".status-dot{width:12px;height:12px;border-radius:50%;position:relative;}"
".status-dot.online{background:#00e676;box-shadow:0 0 10px #00e676;}"
".status-dot.offline{background:#555;}"
".status-dot.pairing{background:#ffab00;box-shadow:0 0 10px #ffab00;}"
".ble-section .ble-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px;}"
".ble-section .ble-title{font-size:13px;font-weight:700;color:#8a8a9e;text-transform:uppercase;letter-spacing:1px;}"
".ble-badge{font-size:11px;font-family:'JetBrains Mono',monospace;padding:3px 10px;border-radius:20px;font-weight:700;}"
".ble-badge.idle{background:rgba(255,255,255,0.05);color:#8a8a9e;}"
".ble-badge.scanning{background:rgba(0,245,212,0.1);color:#00f5d4;animation:pulse 1s infinite;}"
".ble-badge.connected{background:rgba(0,230,118,0.12);color:#00e676;}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.5}}"
".ble-device-card{background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.06);border-radius:12px;padding:12px 14px;margin-bottom:8px;display:flex;align-items:center;gap:12px;}"
".ble-device-card .ble-info{flex:1;}"
".ble-device-card .ble-name{font-size:14px;font-weight:600;color:#fff;}"
".ble-device-card .ble-addr{font-size:10px;color:#8a8a9e;font-family:'JetBrains Mono',monospace;margin-top:2px;}"
".ble-device-card .ble-rssi{font-size:10px;color:#8a8a9e;font-family:'JetBrains Mono',monospace;margin-left:4px;}"
".btn-ble-connect{background:linear-gradient(135deg,#00f5d4,#00bfa5);color:#05020c;border:none;border-radius:8px;padding:7px 14px;font-size:12px;font-weight:700;cursor:pointer;white-space:nowrap;transition:all 0.15s;}"
".btn-ble-connect:active{transform:scale(0.97);}"
".btn-ble-disconnect{background:rgba(233,69,96,0.1);color:#e94560;border:1px solid rgba(233,69,96,0.3);border-radius:8px;padding:7px 14px;font-size:12px;font-weight:700;cursor:pointer;white-space:nowrap;transition:all 0.15s;}"
".btn-ble-disconnect:active{background:rgba(233,69,96,0.2);}"
"/* Controller HUD */"
".ctrl-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px;}"
".ctrl-top .back{background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);color:#fff;border-radius:8px;padding:8px 16px;font-size:13px;font-weight:600;cursor:pointer;}"
".ctrl-top .name{font-size:16px;font-weight:700;color:#00f5d4;}"
".ctrl-container{flex:1;display:flex;flex-direction:column;justify-content:space-between;min-height:0;}"
".ctrl-row{display:flex;flex-direction:row;justify-content:space-around;align-items:center;margin:10px 0;}"
".ctrl-col{display:flex;flex-direction:column;align-items:center;gap:12px;}"
".joystick{width:130px;height:130px;border-radius:50%;background:radial-gradient(circle, rgba(18, 18, 42, 0.8) 0%, rgba(5, 2, 12, 0.9) 100%);border:2px solid rgba(255,255,255,0.1);position:relative;touch-action:none;box-shadow:inset 0 0 20px rgba(0,0,0,0.6);transition:border-color 0.2s;}"
".joystick.active{border-color:#00f5d4;}"
".joystick .knob{width:44px;height:44px;border-radius:50%;background:radial-gradient(circle, #e94560, #a81c3d);position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);pointer-events:none;box-shadow:0 0 15px rgba(233,69,96,0.5);}"
".btn-grid{display:grid;gap:6px;}"
".dpad{grid-template-columns:repeat(3,46px);}"
".face{grid-template-columns:repeat(3,46px);}"
".btn-grid button{height:44px;border:none;border-radius:10px;background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.06);color:#fff;font-size:16px;cursor:pointer;touch-action:none;transition:all 0.15s;}"
".btn-grid button:active, .btn-grid button.active{background:#e94560;border-color:#e94560;box-shadow:0 0 15px rgba(233,69,96,0.6);transform:scale(0.95);}"
".btn-grid .empty{visibility:hidden;}"
".face button{border-radius:50%;background:rgba(255,255,255,0.02);font-weight:bold;}"
".ctrl-bar{display:flex;gap:6px;margin:6px 0;width:100%;justify-content:center;}"
".ctrl-bar button{height:36px;flex:1;max-width:90px;border:none;border-radius:8px;background:rgba(255,255,255,0.04);border:1px solid rgba(255,255,255,0.06);color:#fff;font-size:12px;font-weight:600;cursor:pointer;touch-action:none;transition:all 0.15s;}"
".ctrl-bar button:active, .ctrl-bar button.active{background:#00f5d4;color:#05020c;border-color:#00f5d4;box-shadow:0 0 15px rgba(0,245,212,0.5);}"
".trig-row{display:flex;gap:16px;margin:8px 0;justify-content:center;width:100%;}"
".trig-row label{font-size:12px;color:#8a8a9e;display:flex;align-items:center;gap:8px;flex:1;max-width:160px;}"
".trig-row input[type='range']{-webkit-appearance:none;width:100%;height:6px;border-radius:3px;background:rgba(255,255,255,0.1);outline:none;}"
".trig-row input[type='range']::-webkit-slider-thumb{-webkit-appearance:none;width:16px;height:16px;border-radius:50%;background:#e94560;cursor:pointer;box-shadow:0 0 8px rgba(233,69,96,0.5);}"
".status-card{display:flex;align-items:center;justify-content:space-between;background:rgba(0,245,212,0.05);border:1px solid rgba(0,245,212,0.15);border-radius:12px;padding:10px 14px;margin-bottom:12px;}"
".status-card .status-title{font-size:12px;color:#8a8a9e;font-weight:600;}"
".status-card .status-value{font-size:13px;color:#00f5d4;font-weight:bold;font-family:'JetBrains Mono',monospace;}"
"@media(max-height:600px){.joystick{width:90px;height:90px}.joystick .knob{width:32px;height:32px}.btn-grid button{height:36px;font-size:12px}.dpad,.face{grid-template-columns:repeat(3,38px)}}"
"</style>"
"</head>"
"<body>"

"<!-- PAGE: Device Browser -->"
"<div id='pageBrowser' class='page active'>"
"<div class='header'><h1>Ghostpad <span style='color:#e94560'>Bridge</span></h1><div class='sub'>HACK THE GAMEPAD BOUNDARIES</div></div>"

"<div class='status-card'>"
"<span class='status-title'>CONNECTED CONSOLE</span>"
"<span class='status-value' id='usbConsoleName'>None</span>"
"</div>"

"<!-- Manual Console IP -->"
"<div class='glass-panel'>"
"<div style='display:flex;font-size:13px;color:#8a8a9e;margin-bottom:8px;font-weight:700;letter-spacing:0.5px'><span>🔌 Direct Console Connection</span></div>"
"<div style='display:flex;gap:8px'>"
"<input type='text' id='manualIp' placeholder='PS4 IP (e.g. 192.168.1.50)' style='flex:1;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:12px;padding:14px;color:#fff;font-size:14px;outline:none;font-family:\"JetBrains Mono\",monospace'>"
"<button class='btn-primary' style='flex:0 0 auto;padding:14px 20px;width:auto' onclick='connectManualIp()'>Connect</button>"
"</div>"
"</div>"

"<!-- BLE Controller Section -->"
"<div class='glass-panel ble-section' id='bleSectionPanel'>"
"<div class='ble-header'>"
"<span class='ble-title'>🎮 BT Controller</span>"
"<span class='ble-badge idle' id='bleBadge'>IDLE</span>"
"</div>"
"<div id='bleConnectedCard' style='display:none;margin-bottom:10px'></div>"
"<button class='btn-primary' id='bleScanBtn' onclick='startBleScan()' style='background:linear-gradient(135deg,#00f5d4 0%,#00bfa5 100%);box-shadow:0 4px 15px rgba(0,245,212,0.2);margin-bottom:10px'>🔍 Scan BT Controllers</button>"
"<div id='bleDeviceList'></div>"
"</div>"

"<div class='glass-panel'>"
"<button class='btn-primary' id='scanBtn' onclick='scanDevices()' style='margin-bottom:0'>📡 Subnet Console Scan</button>"
"</div>"

"<div style='display:flex;gap:10px;margin-bottom:12px'>"
"<button class='btn-secondary' style='flex:1' onclick='showPage(\"pageSettings\")'>⚙ Settings</button>"
"<button class='btn-secondary' style='flex:1' onclick='showPage(\"pageKlog\")'>📋 Klog</button>"
"<button class='btn-secondary' style='flex:1' onclick='showPage(\"pageAbout\")'>ℹ About</button>"
"</div>"

"<div class='device-list' id='deviceList'>"
"<div class='device-card' onclick='selectedConsoleIp=\"usb\";document.getElementById(\"ctrlDeviceName\").textContent=\"PlayStation (USB)\";showPage(\"pageController\");'>"
"<div class='icon'>🔗</div>"
"<div class='info'>"
"<div class='name'>PlayStation (USB HID)</div>"
"<div class='desc'>Controlla la console connessa via USB</div>"
"</div>"
"<div class='status-dot offline' id='usbStatusDot'></div>"
"</div>"
"</div>"
"</div>"

"<!-- PAGE: Controller -->"
"<div id='pageController' class='page'>"
"<div class='ctrl-top'>"
"<button class='back' onclick='showPage(\"pageBrowser\")'>← Back</button>"
"<span class='name' id='ctrlDeviceName'>Virtual Controller</span>"
"<span id='ctrlStatus' style=\"font-size:11px;color:#e94560;font-weight:bold;font-family:'JetBrains Mono',monospace\">○ Ready</span>"
"</div>"

"<div class='status-card' id='gamepadStatusCard' style='display:none;background:rgba(233,69,96,0.05);border-color:rgba(233,69,96,0.15)'>"
"<span class='status-title' style='color:#8a8a9e'>PHYSICAL GAMEPAD</span>"
"<span class='status-value' id='connectedGamepadName' style='color:#e94560'>None</span>"
"</div>"

"<div class='ctrl-container'>"
"<div class='ctrl-row'>"
"<div class='ctrl-col'>"
"<div class='joystick' id='joyL'><div class='knob' id='knobL'></div></div>"
"<div class='btn-grid dpad'>"
"<button class='empty'></button><button data-btn='up'>▲</button><button class='empty'></button>"
"<button data-btn='left'>◀</button><button data-btn='down'>▼</button><button data-btn='right'>▶</button>"
"</div>"
"</div>"
"<div class='ctrl-col'>"
"<div class='joystick' id='joyR'><div class='knob' id='knobR'></div></div>"
"<div class='btn-grid face'>"
"<button class='empty'></button><button data-btn='triangle' style='color:#00f5d4'>▲</button><button class='empty'></button>"
"<button data-btn='square' style='color:#ff2a5f'>■</button><button data-btn='cross' style='color:#d883ff'>✕</button><button data-btn='circle' style='color:#81c784'>●</button>"
"</div>"
"</div>"
"</div>"

"<div>"
"<div class='ctrl-bar'>"
"<button data-btn='l1'>L1</button><button data-btn='l2'>L2</button><button data-btn='l3'>L3</button>"
"<button data-btn='r1'>R1</button><button data-btn='r2'>R2</button><button data-btn='r3'>R3</button>"
"</div>"
"<div class='ctrl-bar'>"
"<button data-btn='create'>Create</button><button data-btn='options'>Opt</button>"
"<button data-btn='ps' style='border-color:#e94560'>PS</button><button data-btn='touchpad'>Touch</button>"
"</div>"
"<div class='trig-row'>"
"<label>L2 <input type='range' id='l2val' min='0' max='255' value='0'></label>"
"<label>R2 <input type='range' id='r2val' min='0' max='255' value='0'></label>"
"</div>"
"</div>"
"</div>"
"</div>"

"<!-- PAGE: Settings -->"
"<div id='pageSettings' class='page'>"
"<div class='ctrl-top'><button class='back' onclick='showPage(\"pageBrowser\")'>← Back</button><span class='name'>Settings</span><span></span></div>"
"<div class='glass-panel'>"
"<div style='font-size:13px;color:#8a8a9e;margin-bottom:8px'>ESP32 System Status</div>"
"<div id='espStatus' style=\"font-size:12px;color:#ccc;line-height:1.8;font-family:'JetBrains Mono',monospace\">Loading...</div>"
"</div>"
"<div class='glass-panel'>"
"<div style='font-size:13px;color:#8a8a9e;margin-bottom:8px'>USB Console Interface</div>"
"<div id='usbStatus' style=\"font-size:12px;color:#ccc;line-height:1.8;font-family:'JetBrains Mono',monospace\">Checking...</div>"
"</div>"
"<div class='glass-panel'>"
"<div style='font-size:13px;color:#8a8a9e;margin-bottom:8px'>💾 Payload Manager</div>"
"<div id='payloadStatus' style=\"font-size:12px;color:#ccc;line-height:1.8;font-family:'JetBrains Mono',monospace;margin-bottom:10px\">No payload loaded</div>"
"<input type='file' id='payloadFile' style='display:none' onchange='uploadPayload(this)'>"
"<button class='btn-secondary' style='width:100%;margin-bottom:10px' onclick='document.getElementById(\"payloadFile\").click()'>📤 Upload Payload</button>"
"<div style='display:flex;gap:8px;margin-bottom:6px'>"
"<input type='text' id='targetIp' placeholder='Console IP (e.g. 10.0.0.x)' style='flex:1;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:8px;padding:10px;color:#fff;font-size:13px;outline:none;font-family:\"JetBrains Mono\",monospace'>"
"</div>"
"<div style='display:flex;gap:8px;margin-bottom:8px'>"
"<input type='number' id='targetPort' value='9021' min='1' max='65535' style='flex:0 0 auto;width:120px;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:8px;padding:10px;color:#fff;font-size:13px;outline:none;font-family:\"JetBrains Mono\",monospace'>"
"<button class='btn-primary' style='flex:1;padding:10px 18px' onclick='deployPayload()'>🚀 Deploy</button>"
"</div>"
"<div id='deployLog' style=\"font-size:11px;color:#8a8a9e;line-height:1.6;font-family:'JetBrains Mono',monospace\"></div>"
"</div>"
"</div>"

"<!-- PAGE: About -->"
"<div id='pageAbout' class='page'>"
"<div class='ctrl-top'><button class='back' onclick='showPage(\"pageBrowser\")'>← Back</button><span class='name'>About</span><span></span></div>"
"<div class='glass-panel' style='text-align:center;padding:24px;color:#8a8a9e;font-size:14px;line-height:1.8'>"
"<h2 style='color:#e94560;margin-bottom:14px;font-weight:800'>Ghostpad Bridge</h2>"
"<p>High performance custom ESP32-P4 and ESP32-C6 SDIO Wi-Fi co-processor system.</p>"
"<p style='margin-top:12px'>Connected directly via USB TinyUSB stack to act as a hardware-spoofed game controller.</p>"
"<p style=\"margin-top:16px;font-size:11px;font-family:'JetBrains Mono',monospace\">v1.1 · Waveshare P4 Board</p>"
"</div>"
"</div>"

"<!-- PAGE: Klog Viewer -->"
"<div id='pageKlog' class='page'>"
"<div class='ctrl-top'><button class='back' onclick='showPage(\"pageSettings\")'>← Back</button><span class='name'>📋 Klog Viewer</span><span></span></div>"
"<div class='glass-panel'>"
"<div style='display:flex;gap:8px;margin-bottom:10px'>"
"<input type='text' id='klogIp' placeholder='Console IP' style='flex:1;background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);border-radius:8px;padding:10px;color:#fff;font-size:13px;outline:none;font-family:\"JetBrains Mono\",monospace'>"
"<button class='btn-primary' id='klogConnectBtn' style='flex:0 0 auto;padding:10px 18px;width:auto' onclick='klogConnect()'>🔌 Connect</button>"
"<button class='btn-secondary' id='klogDisconnectBtn' style='flex:0 0 auto;padding:10px 18px;width:auto;display:none' onclick='klogDisconnect()'>⛔ Disconnect</button>"
"</div>"
"<div id='klogStatus' style='font-size:11px;color:#8a8a9e;margin-bottom:8px;font-family:\"JetBrains Mono\",monospace'>Disconnected</div>"
"<div style='display:flex;gap:8px;margin-bottom:8px'>"
"<button class='btn-secondary' style='flex:0 0 auto;padding:6px 14px;font-size:12px' onclick='klogCopy()'>📋 Copy</button>"
"<button class='btn-secondary' style='flex:0 0 auto;padding:6px 14px;font-size:12px' onclick='klogClear()'>🗑 Clear</button>"
"<label style='margin-left:auto;font-size:12px;color:#8a8a9e;display:flex;align-items:center;gap:4px'><input type='checkbox' id='klogAutoScroll' checked onchange=''>Auto-scroll</label>"
"</div>"
"<pre id='klogOutput' style='background:rgba(0,0,0,0.4);border:1px solid rgba(255,255,255,0.06);border-radius:8px;padding:12px;height:50vh;overflow-y:auto;font-family:\"JetBrains Mono\",monospace;font-size:11px;line-height:1.5;color:#00f5d4;white-space:pre-wrap;word-break:break-all'>Waiting for klog data...</pre>"
"</div>"
"</div>"

"<script>"
"const BTN_MAP={"
"cross:1,square:2,circle:4,triangle:8,"
"up:16,right:32,down:64,left:128,"
"l1:256,r1:512,l3:1024,r3:2048,"
"l2:4096,r2:8192,ps:16384,create:32768,"
"options:65536,touchpad:131072"
"};"
"let state={buttons:0,lx:128,ly:128,rx:128,ry:128,l2:0,r2:0};"
"let ws=null;let wsReconnect=null;let activeGamepadIndex=null;let loopId=null;let scanInterval=null;let selectedConsoleIp=null;let controllerStreamTimer=null;let controllerActive=false;let controllerSeq=0;let lastSendAt=0;"

"function showPage(id){"
"document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));"
"document.getElementById(id).classList.add('active');"
"if(id==='pageBrowser'){stopControllerConnection();refreshDevices();startBrowserPoll();}"
"else if(id==='pageController'){stopBrowserPoll();connectWs();startGamepadLoop();startControllerStream();}"
"else {stopBrowserPoll();stopControllerConnection();}"
"if(id==='pageSettings'){refreshSettings();refreshPayloadStatus();}"
"}"

"function setCtrlStatus(text,color){const el=document.getElementById('ctrlStatus');if(el){el.textContent=text;el.style.color=color||'#8a8a9e';}}"
"function openControllerFor(ip,name){selectedConsoleIp=ip;document.getElementById('ctrlDeviceName').textContent=name||'PlayStation (Wi-Fi)';document.getElementById('targetIp').value=ip;showPage('pageController');}"
"function connectWs(){"
"if(!selectedConsoleIp){setCtrlStatus('! No target','#ffab00');return;}"
"if(ws&&(ws.readyState===WebSocket.OPEN||ws.readyState===WebSocket.CONNECTING))return;"
"const p=location.protocol==='https:'?'wss:':'ws:';"
"const u=p+'//'+location.host+'/ws';"
"setCtrlStatus('○ Connecting','#ffab00');"
"ws=new WebSocket(u);"
"ws.onopen=()=>{controllerActive=true;setCtrlStatus('● Streaming','#00f5d4');ws.send(JSON.stringify({target_ip:selectedConsoleIp,hello:'controller'}));sendState(true);startControllerStream();};"
"ws.onmessage=(e)=>{try{const msg=JSON.parse(e.data);if(msg.event==='console_connected')setCtrlStatus('● GPAD '+msg.ip,'#00f5d4');else if(msg.event==='console_error')setCtrlStatus('! '+msg.msg,'#e94560');}catch(_){}};"
"ws.onclose=()=>{setCtrlStatus('○ Closed','#e94560');ws=null;stopControllerStream();if(controllerActive&&document.getElementById('pageController').classList.contains('active')){clearTimeout(wsReconnect);wsReconnect=setTimeout(connectWs,1500);}};"
"ws.onerror=()=>{setCtrlStatus('! WS error','#e94560');ws&&ws.close();};"
"}"

"function startControllerStream(){"
"if(controllerStreamTimer)return;"
"controllerActive=true;"
"controllerStreamTimer=setInterval(()=>sendState(false),33);"
"}"

"function stopControllerStream(){"
"if(controllerStreamTimer){clearInterval(controllerStreamTimer);controllerStreamTimer=null;}"
"}"

"function stopControllerConnection(){"
"controllerActive=false;"
"stopControllerStream();"
"stopGamepadLoop();"
"if(ws){ws.onclose=null;try{sendNeutralState();}catch(_){ }try{ws.close();}catch(_){ }ws=null;}"
"clearTimeout(wsReconnect);wsReconnect=null;"
"}"

"function sendNeutralState(){"
"const old={...state};"
"state.buttons=0;state.lx=128;state.ly=128;state.rx=128;state.ry=128;state.l2=0;state.r2=0;"
"sendState(true);"
"state=old;"
"}"

"function sendState(force){"
"if(!ws||ws.readyState!==WebSocket.OPEN)return;"
"const now=Date.now();"
"if(!force&&now-lastSendAt<20)return;"
"lastSendAt=now;"
"controllerSeq=(controllerSeq+1)>>>0;"
"ws.send(JSON.stringify({...state,target_ip:selectedConsoleIp,seq:controllerSeq,ts:now}));"
"}"

"function updateBtn(btn,press){"
"const bits=BTN_MAP[btn];"
"if(!bits)return;"
"const el=document.querySelector(`[data-btn='${btn}']`);"
"if(press){"
"state.buttons|=bits;"
"if(el)el.classList.add('active');"
"}else{"
"state.buttons&=~bits;"
"if(el)el.classList.remove('active');"
"}"
"sendState();"
"}"

"function setupJoy(id,ox,oy,knobId){"
"const el=document.getElementById(id);"
"const knob=document.getElementById(knobId);"
"let active=false;"
"function mv(e){"
"if(!active)return;"
"const t=e.touches?e.touches[0]:e;"
"const r=el.getBoundingClientRect();"
"const cx=r.left+r.width/2,cy=r.top+r.height/2;"
"const mr=r.width/2-22;"
"let dx=t.clientX-cx,dy=t.clientY-cy;"
"const d=Math.sqrt(dx*dx+dy*dy);"
"if(d>mr){dx=dx/d*mr;dy=dy/d*mr;}"
"knob.style.left=(50+dx/mr*40)+'%';"
"knob.style.top=(50+dy/mr*40)+'%';"
"state[ox]=Math.round(128+dx/mr*127);"
"state[oy]=Math.round(128+dy/mr*127);"
"sendState();"
"}"
"function st(e){active=true;el.classList.add('active');mv(e);}"
"function en(){"
"if(!active)return;"
"active=false;el.classList.remove('active');knob.style.left='50%';knob.style.top='50%';"
"state[ox]=128;state[oy]=128;sendState();"
"}"
"el.addEventListener('touchstart',st,{passive:true});"
"el.addEventListener('touchmove',mv,{passive:true});"
"el.addEventListener('touchend',en);el.addEventListener('touchcancel',en);"
"el.addEventListener('mousedown',st);"
"window.addEventListener('mousemove',mv);window.addEventListener('mouseup',en);"
"}"
"function connectManualIp(){"
"const ip=document.getElementById('manualIp').value.trim();"
"if(!ip){document.getElementById('manualIp').style.borderColor='#e94560';setTimeout(()=>{document.getElementById('manualIp').style.borderColor='rgba(255,255,255,0.1)'},1000);return;}"
"selectedConsoleIp=ip;"
"document.getElementById('ctrlDeviceName').textContent='PlayStation ('+ip+')';"
"showPage('pageController');"
"}"
"setupJoy('joyL','lx','ly','knobL');"
"setupJoy('joyR','rx','ry','knobR');"

"document.querySelectorAll('[data-btn]').forEach(b=>{"
"const btn=b.dataset.btn;"
"b.addEventListener('touchstart',e=>{e.preventDefault();updateBtn(btn,true);},{passive:false});"
"b.addEventListener('touchend',e=>{e.preventDefault();updateBtn(btn,false);});"
"b.addEventListener('touchcancel',e=>{updateBtn(btn,false);});"
"b.addEventListener('mousedown',e=>{updateBtn(btn,true);});"
"b.addEventListener('mouseup',e=>{updateBtn(btn,false);});"
"b.addEventListener('mouseleave',e=>{updateBtn(btn,false);});"
"});"

"document.getElementById('l2val').addEventListener('input',function(){state.l2=parseInt(this.value);sendState();});"
"document.getElementById('r2val').addEventListener('input',function(){state.r2=parseInt(this.value);sendState();});"

"/* Gamepad API implementation */"
"window.addEventListener('gamepadconnected',(e)=>{console.log('Gamepad connected:',e.gamepad.id);activeGamepadIndex=e.gamepad.index;updateGamepadStatus(e.gamepad);});"
"window.addEventListener('gamepaddisconnected',(e)=>{console.log('Gamepad disconnected:',e.gamepad.id);if(activeGamepadIndex===e.gamepad.index){activeGamepadIndex=null;updateGamepadStatus(null);}});"

"function updateGamepadStatus(gp){"
"const card=document.getElementById('gamepadStatusCard');"
"const nameLabel=document.getElementById('connectedGamepadName');"
"if(gp){"
"nameLabel.textContent=gp.id.split('(')[0].trim();"
"card.style.display='flex';"
"}else{"
"card.style.display='none';"
"}"
"}"

"function pollGamepad(){"
"if(activeGamepadIndex===null)return;"
"const gp=navigator.getGamepads()[activeGamepadIndex];"
"if(!gp)return;"
"state.lx=Math.round(128+gp.axes[0]*127);"
"state.ly=Math.round(128+gp.axes[1]*127);"
"state.rx=Math.round(128+gp.axes[2]*127);"
"state.ry=Math.round(128+gp.axes[3]*127);"
"updateJoystickVisual('knobL',gp.axes[0],gp.axes[1]);"
"updateJoystickVisual('knobR',gp.axes[2],gp.axes[3]);"
"let buttons=0;"
"if(gp.buttons[0].pressed){buttons|=BTN_MAP.cross;visualPress('cross',true);}else{visualPress('cross',false);}"
"if(gp.buttons[1].pressed){buttons|=BTN_MAP.circle;visualPress('circle',true);}else{visualPress('circle',false);}"
"if(gp.buttons[2].pressed){buttons|=BTN_MAP.square;visualPress('square',true);}else{visualPress('square',false);}"
"if(gp.buttons[3].pressed){buttons|=BTN_MAP.triangle;visualPress('triangle',true);}else{visualPress('triangle',false);}"
"if(gp.buttons[4].pressed){buttons|=BTN_MAP.l1;visualPress('l1',true);}else{visualPress('l1',false);}"
"if(gp.buttons[5].pressed){buttons|=BTN_MAP.r1;visualPress('r1',true);}else{visualPress('r1',false);}"
"if(gp.buttons[8].pressed){buttons|=BTN_MAP.create;visualPress('create',true);}else{visualPress('create',false);}"
"if(gp.buttons[9].pressed){buttons|=BTN_MAP.options;visualPress('options',true);}else{visualPress('options',false);}"
"if(gp.buttons[10].pressed){buttons|=BTN_MAP.l3;visualPress('l3',true);}else{visualPress('l3',false);}"
"if(gp.buttons[11].pressed){buttons|=BTN_MAP.r3;visualPress('r3',true);}else{visualPress('r3',false);}"
"if(gp.buttons[12].pressed){buttons|=BTN_MAP.up;visualPress('up',true);}else{visualPress('up',false);}"
"if(gp.buttons[13].pressed){buttons|=BTN_MAP.down;visualPress('down',true);}else{visualPress('down',false);}"
"if(gp.buttons[14].pressed){buttons|=BTN_MAP.left;visualPress('left',true);}else{visualPress('left',false);}"
"if(gp.buttons[15].pressed){buttons|=BTN_MAP.right;visualPress('right',true);}else{visualPress('right',false);}"
"if(gp.buttons[16]&&gp.buttons[16].pressed){buttons|=BTN_MAP.ps;visualPress('ps',true);}else{visualPress('ps',false);}"
"if(gp.buttons[17]&&gp.buttons[17].pressed){buttons|=BTN_MAP.touchpad;visualPress('touchpad',true);}else{visualPress('touchpad',false);}"
"state.l2=Math.round(gp.buttons[6].value*255);"
"state.r2=Math.round(gp.buttons[7].value*255);"
"document.getElementById('l2val').value=state.l2;"
"document.getElementById('r2val').value=state.r2;"
"state.buttons=buttons;"
"sendState();"
"}"

"function updateJoystickVisual(knobId,x,y){"
"const knob=document.getElementById(knobId);"
"knob.style.left=(50+x*40)+'%';"
"knob.style.top=(50+y*40)+'%';"
"}"

"function visualPress(btn,press){"
"const el=document.querySelector(`[data-btn='${btn}']`);"
"if(!el)return;"
"if(press)el.classList.add('active');"
"else el.classList.remove('active');"
"}"

"function startGamepadLoop(){"
"if(loopId)return;"
"function l(){pollGamepad();loopId=requestAnimationFrame(l);}"
"loopId=requestAnimationFrame(l);"
"}"

"function stopGamepadLoop(){"
"if(loopId){cancelAnimationFrame(loopId);loopId=null;}"
"}"

"/* BLE native scan (ESP32-side) */"
"async function startBleScan(){"
"const btn=document.getElementById('bleScanBtn');"
"const badge=document.getElementById('bleBadge');"
"const list=document.getElementById('bleDeviceList');"
"btn.disabled=true;btn.textContent='⏳ Scanning...';"
"badge.className='ble-badge scanning';badge.textContent='SCANNING';"
"list.innerHTML='';"
"try{"
"const r=await fetch('/api/ble/scan');"
"const data=await r.json();"
"if(data.synced===false){"
"list.innerHTML='<div style=\"color:#ffab00;font-size:12px;padding:10px 0\">⚠ BLE host not synced yet. The ESP32-C6 co-processor may still be initializing. Wait a few seconds and retry.</div>';"
"}"
"else if(data.scan_ok===false){"
"list.innerHTML='<div style=\"color:#e94560;font-size:12px;padding:10px 0\">✗ BLE scan failed: '+(data.error||'unknown')+'. The C6 BT controller may not be available.</div>';"
"}"
"else{"
"renderBleDevices(data.devices||[],data);"
"}"
"}catch(e){"
"list.innerHTML='<div style=\"color:#e94560;font-size:12px;padding:10px 0\">Scan error: '+e.message+'</div>';"
"}"
"btn.disabled=false;btn.textContent='🔍 Scan BLE Controllers';"
"badge.className='ble-badge idle';badge.textContent='IDLE';"
"}"

"function renderBleDevices(list,data){"
"const el=document.getElementById('bleDeviceList');"
"el.innerHTML='';"
"if(data&&data.connected){"
"renderBleConnected(data.device_name,data.device_addr);"
"return;"
"}"
"if(!list||list.length===0){"
"el.innerHTML='<div style=\"color:#8a8a9e;font-size:12px;text-align:center;padding:12px 0\">No BLE gamepads found. Make sure the controller is in pairing mode.</div>';"
"return;"
"}"
"list.forEach(d=>{"
"const card=document.createElement('div');"
"card.className='ble-device-card';"
"card.innerHTML='"
"<div class=\"ble-info\">"
"<div class=\"ble-name\">'+d.name+' <span class=\"ble-rssi\">'+d.rssi+'dBm</span></div>'"
"+'<div class=\"ble-addr\">'+d.addr+'</div></div>'"
"+'<button class=\"btn-ble-connect\" onclick=\"connectBle(\\''+d.addr+'\\',\\''+d.name+'\\')\" >Connect</button>'"
";"
"el.appendChild(card);"
"});"
"}"

"async function connectBle(addr,name){"
"const badge=document.getElementById('bleBadge');"
"badge.className='ble-badge scanning';badge.textContent='CONNECTING';"
"try{"
"const r=await fetch('/api/ble/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({addr})});"
"const data=await r.json();"
"if(data.ok){"
"renderBleConnected(name,addr);"
"}else{"
"badge.className='ble-badge idle';badge.textContent='FAILED';"
"}"
"}catch(e){"
"badge.className='ble-badge idle';badge.textContent='ERROR';"
"}"
"}"

"function renderBleConnected(name,addr){"
"const badge=document.getElementById('bleBadge');"
"badge.className='ble-badge connected';badge.textContent='CONNECTED';"
"const list=document.getElementById('bleDeviceList');"
"list.innerHTML='';"
"const cc=document.getElementById('bleConnectedCard');"
"cc.style.display='block';"
"cc.innerHTML='"
"<div class=\"ble-device-card\" style=\"border-color:rgba(0,230,118,0.25);background:rgba(0,230,118,0.04)\">"
"<div class=\"ble-info\"><div class=\"ble-name\">'+name+'</div><div class=\"ble-addr\">'+addr+'</div></div>'"
"+'<button class=\"btn-ble-disconnect\" onclick=\"disconnectBle()\">Disconnect</button>'"
"+'</div>';"
"}"

"async function disconnectBle(){"
"await fetch('/api/ble/disconnect',{method:'POST'});"
"document.getElementById('bleConnectedCard').style.display='none';"
"document.getElementById('bleDeviceList').innerHTML='';"
"const badge=document.getElementById('bleBadge');"
"badge.className='ble-badge idle';badge.textContent='IDLE';"
"}"

"async function refreshBleStatus(){"
"try{"
"const r=await fetch('/api/ble/status');"
"const data=await r.json();"
"if(data.connected){"
"renderBleConnected(data.device_name,data.device_addr);"
"}else{"
"const badge=document.getElementById('bleBadge');"
"if(badge.textContent==='CONNECTED'){"
"badge.className='ble-badge idle';badge.textContent='IDLE';"
"document.getElementById('bleConnectedCard').style.display='none';"
"}"
"}"
"}catch(e){}"
"}"

"async function scanDevices(){"
"const btn=document.getElementById('scanBtn');"
"btn.disabled=true;btn.textContent='Scanning...';"
"try{"
"const r=await fetch('/api/scan');"
"const data=await r.json();"
"renderDevices(data.devices);"
"}catch(e){"
"document.getElementById('deviceList').innerHTML='<div style=\"text-align:center;color:#e94560;padding:40px 0;font-size:13px\">Scan failed: '+e.message+'</div>';"
"}"
"btn.disabled=false;btn.textContent='🔍 Subnet Console Scan';"
"}"
""
"async function refreshDevices(){"
"try{"
"const statusReq=await fetch('/api/status');"
"const statusData=await statusReq.json();"
"if(statusData.wifi_console&&statusData.wifi_console.connected){"
"document.getElementById('usbConsoleName').textContent='WiFi: '+statusData.wifi_console.ip;"
"}else{"
"document.getElementById('usbConsoleName').textContent=statusData.usb.device||'None';"
"}"
"const usbDot=document.getElementById('usbStatusDot');"
"if(usbDot){"
"if(statusData.usb.connected){"
"usbDot.className='status-dot online';"
"}else{"
"usbDot.className='status-dot offline';"
"}"
"}"
"const wfid='wifi-active-card';"
"let wcard=document.getElementById(wfid);"
"if(statusData.wifi_console&&statusData.wifi_console.connected){"
"if(!wcard){"
"wcard=document.createElement('div');"
"wcard.id=wfid;"
"wcard.className='device-card';"
"wcard.onclick=()=>openControllerFor(statusData.wifi_console.ip,'PlayStation (Wi-Fi)');"
"wcard.innerHTML=\'<div class=\"icon\">🎮</div><div class=\"info\"><div class=\"name\">PlayStation (Wi-Fi)</div><div class=\"desc\">\'+statusData.wifi_console.ip+\' | Connected</div></div><div class=\"status-dot online\"></div>\';"
"document.getElementById(\'deviceList\').appendChild(wcard);"
"}"
"}else{"
"if(wcard)wcard.remove();"
"}"
"}catch(e){}"
"}"
""
"function renderDevices(list){"
"const target=document.getElementById('deviceList');"
"target.innerHTML='';"
"const usbCard=document.createElement('div');"
"usbCard.className='device-card';"
"usbCard.onclick=()=>openControllerFor('usb','PlayStation (USB HID)');"
"usbCard.innerHTML='<div class=\"icon\">🔗</div><div class=\"info\"><div class=\"name\">PlayStation (USB HID)</div><div class=\"desc\">Controlla la console connessa via USB</div></div><div class=\"status-dot offline\" id=\"usbStatusDot\"></div>';"
"target.appendChild(usbCard);"
"if(list&&list.length>0){"
"list.forEach(d=>{"
"if(d.ip==='usb:0')return;"
"const card=document.createElement('div');"
"card.className='device-card';"
"const statusClass=d.status==='online'?'online':(d.status==='pairing'?'pairing':'offline');"

"/* Parse desc to find open ports */"
"const desc=d.desc||'';"
"const hasElf=desc.includes('ELF:✓');"
"const hasKlog=desc.includes('KLOG:✓');"
"const hasGpad=desc.includes('GPAD:✓');"
"const has9090=desc.includes('9090:✓');"

"card.innerHTML=''"
"+'<div class=\"icon\">'+(d.icon||'🎮')+'</div>'"
"+'<div class=\"info\"><div class=\"name\">'+d.name+'</div><div class=\"desc\">'+d.desc+'</div>'"
"+'<div style=\"display:flex;gap:4px;margin-top:6px\">'"
"+(hasElf?'<button class=\"btn-ble-connect\" style=\"width:auto;padding:4px 10px;font-size:10px\" onclick=\"event.stopPropagation();deployToConsole(\\''+d.ip+'\\',9021)\">ELF 9021</button>':'')"
"+(hasGpad?'<button class=\"btn-ble-connect\" style=\"width:auto;padding:4px 10px;font-size:10px;background:linear-gradient(135deg,#00f5d4,#00bfa5)\" onclick=\"event.stopPropagation();openControllerFor(\\''+d.ip+'\\',\\''+(d.name||'PlayStation')+'\\')\">Control</button>':'')"
"+(hasKlog?'<button class=\"btn-ble-connect\" style=\"width:auto;padding:4px 10px;font-size:10px;background:linear-gradient(135deg,#ffab00,#ff6d00)\" onclick=\"event.stopPropagation();openKlogFor(\\''+d.ip+'\\')\">Klog</button>':'')"
"+(has9090?'<button class=\"btn-ble-connect\" style=\"width:auto;padding:4px 10px;font-size:10px;background:linear-gradient(135deg,#aa66ff,#8833dd)\" onclick=\"event.stopPropagation();deployToConsole(\\''+d.ip+'\\',9090)\">9090</button>':'')"
"+'</div></div>'"
"+'<div class=\"status-dot '+statusClass+'\"></div>';"
"card.onclick=()=>openControllerFor(d.ip,d.name);"
"target.appendChild(card);"
"});"
"}"
"}"

"function startBrowserPoll(){"
"if(!scanInterval){scanInterval=setInterval(()=>{refreshDevices();refreshBleStatus();},5000);}"
"}"

"function stopBrowserPoll(){"
"if(scanInterval){clearInterval(scanInterval);scanInterval=null;}"
"}"

"async function uploadPayload(input){"
"const file=input.files[0];"
"if(!file)return;"
"const log=document.getElementById('deployLog');"
"log.innerHTML='Uploading '+file.name+' ('+file.size+' bytes)...';"
"try{"
"const r=await fetch('/api/payload',{method:'POST',body:file,headers:{'Content-Disposition':'filename=\"'+file.name+'\"'}});"
"const data=await r.json();"
"if(data.ok){"
"log.innerHTML='<span style=\"color:#00e676\">✓ Payload uploaded: '+file.name+'</span>';"
"refreshPayloadStatus();"
"}else{"
"log.innerHTML='<span style=\"color:#e94560\">✗ Upload failed</span>';"
"}"
"}catch(e){"
"log.innerHTML='<span style=\"color:#e94560\">✗ Upload error: '+e.message+'</span>';"
"}"
"input.value='';"
"}"

"async function deployPayload(){"
"const ip=document.getElementById('targetIp').value.trim();"
"const port=parseInt(document.getElementById('targetPort').value)||9021;"
"const log=document.getElementById('deployLog');"
"if(!ip){log.innerHTML='<span style=\"color:#ffab00\">⚠ Enter a console IP address</span>';return;}"
"log.innerHTML='<span style=\"color:#00f5d4\">⟳ Deploying to '+ip+':'+port+'...</span>';"
"try{"
"const r=await fetch('/api/deploy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip:ip,port:port})});"
"const data=await r.json();"
"if(data.ok){"
"log.innerHTML='<span style=\"color:#00e676\">✓ Deployed '+data.sent+'/'+data.total+' bytes to '+ip+':'+port+'</span>';"
"}else{"
"log.innerHTML='<span style=\"color:#e94560\">✗ Deploy failed: '+(data.error||'unknown')+'</span>';"
"}"
"}catch(e){"
"log.innerHTML='<span style=\"color:#e94560\">✗ Deploy error: '+e.message+'</span>';"
"}"
"}"

"async function deployToConsole(ip,port){"
"port=port||9021;"
"document.getElementById('targetIp').value=ip;"
"document.getElementById('targetPort').value=port;"
"const log=document.getElementById('deployLog');"
"log.innerHTML='<span style=\"color:#00f5d4\">⟳ Deploying to '+ip+':'+port+'...</span>';"
"try{"
"const r=await fetch('/api/deploy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ip:ip,port:port})});"
"const data=await r.json();"
"if(data.ok){"
"log.innerHTML='<span style=\"color:#00e676\">✓ Deployed '+data.sent+'/'+data.total+' bytes to '+ip+':'+port+'</span>';"
"}else{"
"log.innerHTML='<span style=\"color:#e94560\">✗ Deploy failed: '+(data.error||'unknown')+'</span>';"
"}"
"}catch(e){"
"log.innerHTML='<span style=\"color:#e94560\">✗ Deploy error: '+e.message+'</span>';"
"}"
"}"

"async function refreshPayloadStatus(){"
"try{"
"const r=await fetch('/api/payload');"
"const data=await r.json();"
"const el=document.getElementById('payloadStatus');"
"if(data.loaded){"
"el.innerHTML='<span style=\"color:#00e676\">✓ Loaded:</span> '+data.name+' <span style=\"color:#8a8a9e\">('+data.size+' bytes)</span>';"
"}else{"
"el.innerHTML='<span style=\"color:#8a8a9e\">○ No payload loaded</span>';"
"}"
"}catch(e){}"
"}"

"async function refreshSettings(){"
"try{"
"const r=await fetch('/api/status');"
"const data=await r.json();"
"document.getElementById('espStatus').innerHTML='<div>WiFi AP SSID: '+data.wifi_ssid+'</div><div>Local IP: '+data.ip+'</div><div>Connected Clients: '+data.clients+'</div><div>Uptime: '+data.uptime+'s</div>';"
"document.getElementById('usbStatus').innerHTML='<div>Emulated controller: '+(data.usb.device||'None')+'</div><div>Connected to Host: '+(data.usb.connected?'Yes':'No')+'</div>';"
"}catch(e){"
"document.getElementById('espStatus').textContent='Error loading status';"
"}"
"}"

"/* === Klog Viewer === */"
"let klogWs=null;let klogBuf='';"
"function openKlogFor(ip){document.getElementById('klogIp').value=ip;showPage('pageKlog');setTimeout(klogConnect,150);}"
"function klogConnect(){"
"const ip=document.getElementById('klogIp').value.trim();\n"
"if(!ip){document.getElementById('klogStatus').textContent='! Enter a console IP';return}\n"
"klogDisconnect();\n"
"const proto=location.protocol==='https:'?'wss:':'ws:';\n"
"klogWs=new WebSocket(proto+'//'+location.host+'/ws/klog');\n"
"klogWs.onopen=()=>{\n"
"document.getElementById('klogStatus').textContent='. Connected to '+ip+':3232';\n"
"document.getElementById('klogConnectBtn').style.display='none';\n"
"document.getElementById('klogDisconnectBtn').style.display='inline-block';\n"
"document.getElementById('klogOutput').textContent='';klogBuf='';\n"
"klogWs.send(JSON.stringify({cmd:'connect',ip:ip}));\n"
"};\n"
"klogWs.onmessage=(e)=>{\n"
"const el=document.getElementById('klogOutput');\n"
"if(e.data instanceof Blob){\n"
"const reader=new FileReader();\n"
"reader.onload=()=>{klogAppend(reader.result)};\n"
"reader.readAsText(e.data);\n"
"}else{klogAppend(e.data)}\n"
"};\n"
"klogWs.onclose=()=>{klogCleanup();document.getElementById('klogStatus').textContent='x Disconnected'};\n"
"klogWs.onerror=()=>{klogCleanup();document.getElementById('klogStatus').textContent='x WebSocket error'};\n"
"}\n"
"function klogAppend(text){\n"
"klogBuf+=text;\n"
"const el=document.getElementById('klogOutput');\n"
"el.textContent=klogBuf;\n"
"if(document.getElementById('klogAutoScroll').checked){\n"
"el.scrollTop=el.scrollHeight\n"
"}\n"
"}\n"
"function klogDisconnect(){\n"
"if(klogWs){klogWs.send(JSON.stringify({cmd:'disconnect'}));klogWs.close();klogWs=null}\n"
"klogCleanup()\n"
"}\n"
"function klogCleanup(){\n"
"document.getElementById('klogConnectBtn').style.display='inline-block';\n"
"document.getElementById('klogDisconnectBtn').style.display='none';\n"
"document.getElementById('klogStatus').textContent='Disconnected';\n"
"if(klogWs){klogWs.onclose=null;klogWs.close();klogWs=null}\n"
"}\n"
"function klogCopy(){\n"
"if(klogBuf){\n"
"navigator.clipboard.writeText(klogBuf).catch(()=>{\n"
"const ta=document.createElement('textarea');ta.value=klogBuf;document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta)\n"
"});\n"
"}\n"
"}\n"
"function klogClear(){klogBuf='';document.getElementById('klogOutput').textContent=''}\n"

"window.addEventListener('beforeunload',()=>{try{sendNeutralState();}catch(_){}});"
"startBrowserPoll();"
"showPage('pageBrowser');"
"</script>"
"</body></html>";
